import 'dotenv/config';
import * as dotenv from 'dotenv';
import { resolve } from 'path';
import { createClient } from '@supabase/supabase-js';
import { randomUUID } from 'crypto';

dotenv.config({ path: resolve(__dirname, '..', '.env.local') });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

interface Q {
  id: string;
  section: string;
  category: string;
  subcategory: string | null;
  difficulty: string;
  type: string;
  stem: string;
  stimulus: string | null;
  options: { label: string; text: string; isCorrect: boolean }[];
  correct_answer: string;
  explanation: string;
  common_mistakes: { label: string; explanation: string }[];
  skills: string[];
  tags: string[];
  review_status: string;
}

function mc(stem: string, category: string, section: string, difficulty: string,
  optA: string, optB: string, optC: string, optD: string, correct: string,
  explanation: string, mistakes: [string, string][], stimulus?: string): Q {
  return {
    id: randomUUID(),
    section,
    category,
    subcategory: null,
    difficulty,
    type: 'multiple_choice',
    stem,
    stimulus: stimulus || null,
    options: [
      { label: 'A', text: optA, isCorrect: correct === 'A' },
      { label: 'B', text: optB, isCorrect: correct === 'B' },
      { label: 'C', text: optC, isCorrect: correct === 'C' },
      { label: 'D', text: optD, isCorrect: correct === 'D' },
    ],
    correct_answer: correct,
    explanation,
    common_mistakes: mistakes.map(([l, e]) => ({ label: l, explanation: e })),
    skills: [category],
    tags: [section, category.split('.').pop()!],
    review_status: 'published',
  };
}

const questions: Q[] = [
  // ── MATH-ALGEBRA (9 needed) ──────────────────────────────────────────
  mc('Solve for x: 3x + 7 = 22', 'math.algebra.linear_equations', 'math', '1',
    '3', '5', '7', '15', 'B', '3x + 7 = 22 → 3x = 15 → x = 5',
    [['A', 'Divided 22 by 7'], ['D', 'Subtracted 7 but forgot to divide']]),
  mc('If 2(x - 3) = 14, what is x?', 'math.algebra.linear_equations', 'math', '2',
    '4', '7', '10', '11', 'C', '2(x-3)=14 → x-3=7 → x=10',
    [['B', 'Forgot to add 3 back'], ['D', 'Added 3 to 14 then divided']]),
  mc('Simplify: 4(2x + 3) - 2(x - 1)', 'math.algebra.expressions', 'math', '2',
    '6x + 14', '6x + 10', '10x + 14', '6x + 12', 'A',
    '8x + 12 - 2x + 2 = 6x + 14',
    [['B', 'Distributed -2 incorrectly to get -2'], ['C', 'Did not subtract 2x']]),
  mc('Solve the system: x + y = 10, x - y = 4', 'math.algebra.systems', 'math', '2',
    'x=7, y=3', 'x=6, y=4', 'x=8, y=2', 'x=5, y=5', 'A',
    'Add equations: 2x = 14, x = 7, y = 3',
    [['B', 'Subtracted instead of adding'], ['C', 'Arithmetic error']]),
  mc('What is the value of 5x - 2 when x = -3?', 'math.algebra.expressions', 'math', '1',
    '-17', '-13', '-7', '13', 'A', '5(-3) - 2 = -15 - 2 = -17',
    [['B', 'Computed 5(-3) as -13'], ['D', 'Forgot the negative sign']]),
  mc('Solve: x/4 + 3 = 8', 'math.algebra.linear_equations', 'math', '1',
    '12', '20', '44', '2', 'B', 'x/4 = 5 → x = 20',
    [['A', 'Subtracted then multiplied incorrectly'], ['C', 'Multiplied 8+3 by 4']]),
  mc('If 3a + 2b = 19 and a = 3, what is b?', 'math.algebra.systems', 'math', '1',
    '4', '5', '7', '10', 'B', '3(3) + 2b = 19 → 9 + 2b = 19 → 2b = 10 → b = 5',
    [['A', 'Divided 19-9 by 3 instead of 2'], ['C', 'Subtracted incorrectly']]),
  mc('A store sells notebooks for $3 each and pens for $1.50 each. If Maya buys n notebooks and p pens, which expression represents the total cost?', 'math.algebra.expressions', 'math', '2',
    '3n + 1.5p', '4.5np', '3p + 1.5n', '(3 + 1.5)(n + p)', 'A',
    'Cost = price × quantity for each item: 3n + 1.5p',
    [['B', 'Multiplied prices and quantities together'], ['D', 'Added prices and quantities separately']]),
  mc('Which equation has no solution?', 'math.algebraic_modeling', 'math', '3',
    '2x + 1 = 2x + 1', '3x - 5 = 3x + 2', 'x + 4 = 2x', '5x = 0', 'B',
    '3x - 5 = 3x + 2 → -5 = 2, which is false. No value of x satisfies this.',
    [['A', 'This is an identity (infinite solutions)'], ['D', 'This has solution x=0']]),

  // ── MATH-EXPONENTS (5 needed) ────────────────────────────────────────
  mc('What is (3²)³?', 'math.algebra.exponents', 'math', '2',
    '27', '729', '243', '81', 'B', '(3²)³ = 3⁶ = 729',
    [['A', 'Computed 3³ only'], ['C', 'Computed 3⁵']]),
  mc('Simplify: 5⁴ ÷ 5²', 'math.algebra.exponents', 'math', '1',
    '5', '25', '125', '5²', 'B', '5⁴ ÷ 5² = 5² = 25',
    [['C', 'Computed 5³'], ['A', 'Divided exponents: 4÷2=2, then took 5¹']]),
  mc('Express 0.00045 in scientific notation.', 'math.scientific_notation', 'math', '2',
    '4.5 × 10⁻⁴', '45 × 10⁻⁵', '4.5 × 10⁻³', '0.45 × 10⁻³', 'A',
    'Move decimal 4 places right: 4.5 × 10⁻⁴',
    [['C', 'Only moved 3 places'], ['B', 'Coefficient must be between 1 and 10']]),
  mc('What is 2⁻³?', 'math.algebra.exponents', 'math', '2',
    '-8', '-6', '1/8', '1/6', 'C', '2⁻³ = 1/2³ = 1/8',
    [['A', 'Negative exponent doesn\'t make the base negative'], ['B', 'Multiplied instead of raised to power']]),
  mc('If 10ⁿ = 100,000, what is n?', 'math.algebra.exponents', 'math', '1',
    '4', '5', '6', '10', 'B', '100,000 = 10⁵, so n = 5',
    [['A', 'Miscounted zeros'], ['C', 'Counted the 1 as a zero']]),

  // ── MATH-INEQUALITIES (7 needed) ─────────────────────────────────────
  mc('Solve: 2x - 5 > 9', 'math.algebra.inequalities', 'math', '1',
    'x > 2', 'x > 7', 'x > 14', 'x < 7', 'B', '2x > 14 → x > 7',
    [['A', 'Divided 9 by 5'], ['D', 'Flipped inequality incorrectly']]),
  mc('Solve: -3x ≤ 12', 'math.algebra.inequalities', 'math', '2',
    'x ≤ -4', 'x ≥ -4', 'x ≤ 4', 'x ≥ 4', 'B',
    'Dividing by -3 flips the inequality: x ≥ -4',
    [['A', 'Forgot to flip when dividing by negative'], ['C', 'Sign error']]),
  mc('What is |−7| + |3|?', 'math.algebra.absolute_value', 'math', '1',
    '4', '-4', '10', '-10', 'C', '|−7| = 7, |3| = 3, 7 + 3 = 10',
    [['A', 'Subtracted instead of adding'], ['D', 'Kept the negative']]),
  mc('Solve: |x - 2| = 5', 'math.algebra.absolute_value', 'math', '2',
    'x = 7 only', 'x = -3 only', 'x = 7 or x = -3', 'x = 3 or x = -7', 'C',
    'x - 2 = 5 → x = 7, or x - 2 = -5 → x = -3',
    [['A', 'Only found positive case'], ['D', 'Set up equations incorrectly']]),
  mc('Which value of x satisfies both x > -2 and x ≤ 5?', 'math.algebra.inequalities', 'math', '1',
    '-3', '-2', '6', '3', 'D', '3 is greater than -2 and at most 5',
    [['A', '-3 is not greater than -2'], ['C', '6 is not ≤ 5']]),
  mc('Solve: 4 - x < 10', 'math.algebra.inequalities', 'math', '2',
    'x < 6', 'x > -6', 'x < -6', 'x > 6', 'B', '-x < 6 → x > -6',
    [['A', 'Forgot to flip inequality when dividing by -1'], ['C', 'Sign errors']]),
  mc('If |2x + 1| ≤ 7, which describes all solutions?', 'math.arithmetic.absolute_value', 'math', '3',
    '-4 ≤ x ≤ 3', '-3 ≤ x ≤ 4', '-4 ≤ x ≤ 4', '-3 ≤ x ≤ 3', 'A',
    '-7 ≤ 2x+1 ≤ 7 → -8 ≤ 2x ≤ 6 → -4 ≤ x ≤ 3',
    [['D', 'Divided 7 by 2 for both bounds'], ['B', 'Swapped the bounds']]),

  // ── MATH-RATIOS (14 needed) ──────────────────────────────────────────
  mc('If the ratio of boys to girls in a class is 3:5 and there are 40 students, how many boys are there?', 'math.arithmetic.ratios_proportions', 'math', '1',
    '15', '24', '25', '12', 'A', '3/(3+5) × 40 = 3/8 × 40 = 15',
    [['C', 'Used 5/8 instead of 3/8'], ['B', 'Used 3/5 instead of 3/8']]),
  mc('A recipe calls for 2 cups flour for every 3 cups sugar. How much flour is needed for 12 cups sugar?', 'math.arithmetic.ratios_proportions', 'math', '1',
    '6', '8', '18', '4', 'B', '2/3 = x/12 → x = 8',
    [['A', 'Divided 12 by 2'], ['C', 'Multiplied 12 by 3/2']]),
  mc('A shirt originally costs $40 and is on sale for 25% off. What is the sale price?', 'math.arithmetic.percent_change', 'math', '1',
    '$10', '$15', '$30', '$35', 'C', '25% of 40 = 10, sale price = 40 - 10 = 30',
    [['A', 'Gave the discount amount, not the sale price'], ['D', 'Calculated 25% incorrectly']]),
  mc('A population grew from 500 to 650. What is the percent increase?', 'math.arithmetic.percent_change', 'math', '2',
    '23%', '25%', '30%', '35%', 'C', '(650-500)/500 × 100 = 150/500 × 100 = 30%',
    [['A', 'Divided by 650 instead of 500'], ['B', 'Rounded incorrectly']]),
  mc('If 60% of a number is 42, what is the number?', 'math.proportional_reasoning', 'math', '2',
    '25.2', '60', '70', '102', 'C', '0.60 × n = 42 → n = 42/0.60 = 70',
    [['A', 'Multiplied 42 × 0.60'], ['B', 'Confused percent with the number']]),
  mc('The scale on a map is 1 cm = 25 km. Two cities are 3.5 cm apart. What is the actual distance?', 'math.proportional_reasoning', 'math', '1',
    '75 km', '87.5 km', '80 km', '7.14 km', 'B', '3.5 × 25 = 87.5 km',
    [['A', 'Multiplied 3 × 25 only'], ['D', 'Divided instead of multiplied']]),
  mc('A store marks up items by 40%. If the wholesale price is $50, what is the retail price?', 'math.arithmetic.percent_change', 'math', '2',
    '$70', '$90', '$20', '$45', 'A', '40% of 50 = 20, retail = 50 + 20 = 70',
    [['B', 'Applied 40% twice'], ['C', 'Gave the markup amount only']]),
  mc('In a school, 240 out of 800 students play sports. What percentage is this?', 'math.proportional_reasoning', 'math', '1',
    '25%', '30%', '33%', '35%', 'B', '240/800 × 100 = 30%',
    [['A', 'Divided incorrectly'], ['C', 'Rounded up too much']]),
  mc('If a car travels 180 miles using 6 gallons, how many gallons are needed for 300 miles?', 'math.arithmetic.ratios_proportions', 'math', '2',
    '8', '10', '12', '15', 'B', 'Rate = 30 mpg, 300/30 = 10 gallons',
    [['A', 'Divided 300 by 36'], ['C', 'Multiplied 6 by 2']]),
  mc('A $200 item is discounted by 15%, then taxed at 8%. What is the final price?', 'math.arithmetic.percent_change', 'math', '3',
    '$170', '$183.60', '$186', '$179.20', 'B', 'After 15% off: $170. Tax: 170 × 1.08 = $183.60',
    [['A', 'Forgot tax'], ['C', 'Applied tax to original price']]),
  mc('If 3/5 of the students are girls and there are 45 girls, how many students are there in total?', 'math.arithmetic.ratios_proportions', 'math', '1',
    '60', '75', '90', '27', 'B', '3/5 × n = 45 → n = 45 × 5/3 = 75',
    [['A', 'Divided 45 by 3/4'], ['D', 'Multiplied 45 by 3/5']]),
  mc('A mixture is 2 parts red paint to 5 parts blue paint. How much blue paint is needed for 6 liters of red?', 'math.arithmetic.ratios_proportions', 'math', '2',
    '12 liters', '15 liters', '10 liters', '18 liters', 'B', '2/5 = 6/x → x = 15',
    [['A', 'Multiplied 6 by 2'], ['C', 'Multiplied 6 by 5/3']]),
  mc('Tina scored 85% on a 60-question test. How many did she get correct?', 'math.proportional_reasoning', 'math', '1',
    '48', '51', '54', '42', 'B', '0.85 × 60 = 51',
    [['A', 'Computed 0.80 × 60'], ['C', 'Computed 0.90 × 60']]),
  mc('A price increases from $80 to $100. What is the percent increase?', 'math.arithmetic.percent_change', 'math', '1',
    '20%', '25%', '80%', '125%', 'B', '(100-80)/80 × 100 = 25%',
    [['A', 'Divided change by new price instead of original'], ['C', 'Computed 80/100']]),

  // ── MATH-ARITHMETIC (10 needed) ──────────────────────────────────────
  mc('What is 3/4 + 2/3?', 'math.arithmetic.fractions', 'math', '1',
    '5/7', '17/12', '5/12', '1', 'B', '9/12 + 8/12 = 17/12',
    [['A', 'Added numerators and denominators'], ['C', 'Subtracted instead of adding']]),
  mc('What is 0.375 as a fraction in simplest form?', 'math.arithmetic.decimals', 'math', '2',
    '3/8', '375/100', '37/100', '3/10', 'A', '0.375 = 375/1000 = 3/8',
    [['B', 'Didn\'t simplify'], ['D', 'Rounded incorrectly']]),
  mc('What is the GCF of 36 and 48?', 'math.number_theory.divisibility', 'math', '2',
    '6', '8', '12', '24', 'C', 'Factors of 36: 1,2,3,4,6,9,12,18,36. Factors of 48: 1,2,3,4,6,8,12,16,24,48. GCF = 12',
    [['A', 'Found a common factor but not the greatest'], ['D', 'This is a factor of 48 but not 36']]),
  mc('Is 91 prime or composite?', 'math.number_theory.divisibility', 'math', '2',
    'Prime', 'Composite (7 × 13)', 'Composite (9 × 11)', 'Neither', 'B',
    '91 = 7 × 13, so it is composite.',
    [['A', '91 looks prime but is divisible by 7'], ['C', '9 × 11 = 99, not 91']]),
  mc('What is 7/8 - 1/3?', 'math.arithmetic.fractions', 'math', '2',
    '6/5', '13/24', '1/2', '6/24', 'B', '21/24 - 8/24 = 13/24',
    [['A', 'Subtracted numerators and denominators separately'], ['D', 'Didn\'t find common denominator']]),
  mc('Evaluate: 8 + 2 × 3² - 4', 'math.arithmetic.order_of_operations', 'math', '2',
    '22', '86', '26', '30', 'A', '8 + 2(9) - 4 = 8 + 18 - 4 = 22',
    [['C', 'Added 8+2 first'], ['B', 'Did (8+2) × 3² - 4']]),
  mc('What is the LCM of 6 and 8?', 'math.number_theory.divisibility', 'math', '1',
    '14', '24', '48', '2', 'B', 'Multiples: 6,12,18,24... and 8,16,24... LCM = 24',
    [['A', 'Added instead of finding LCM'], ['C', 'Multiplied 6 × 8']]),
  mc('Which number is divisible by both 3 and 4?', 'math.number_theory.divisibility', 'math', '1',
    '8', '9', '24', '15', 'C', '24 ÷ 3 = 8 ✓, 24 ÷ 4 = 6 ✓',
    [['A', '8 is only divisible by 4'], ['B', '9 is only divisible by 3']]),
  mc('Convert 5/6 to a decimal (rounded to nearest hundredth).', 'math.arithmetic.decimals', 'math', '2',
    '0.83', '0.85', '0.56', '0.80', 'A', '5 ÷ 6 = 0.8333... ≈ 0.83',
    [['B', 'Rounded incorrectly'], ['C', 'Divided wrong way']]),
  mc('Evaluate: (12 - 4) ÷ 2 + 3 × 5', 'math.arithmetic.order_of_operations', 'math', '2',
    '19', '35', '23', '17', 'A', '(8) ÷ 2 + 15 = 4 + 15 = 19',
    [['B', 'Did 12 - 4 ÷ 2 + 3 × 5 without parentheses'], ['C', 'Did (8÷2+3) × 5']]),

  // ── MATH-GEOMETRY-SHAPES (5 needed) ──────────────────────────────────
  mc('In a right triangle, one angle is 35°. What is the other acute angle?', 'math.geometry.angles', 'math', '1',
    '45°', '55°', '65°', '145°', 'B', '180 - 90 - 35 = 55°',
    [['A', 'Assumed 45-45-90'], ['D', 'Subtracted from 180 without the right angle']]),
  mc('What is the area of a circle with diameter 10?', 'math.geometry.circles', 'math', '2',
    '25π', '100π', '50π', '10π', 'A', 'r = 5, A = π(5²) = 25π',
    [['B', 'Used diameter as radius'], ['C', 'Used A = πd²/2']]),
  mc('A ladder leans against a wall. The foot is 6 ft from the wall, the ladder is 10 ft. How high does it reach?', 'math.geometry.pythagorean_theorem', 'math', '2',
    '4 ft', '8 ft', '16 ft', '√136 ft', 'B', '10² - 6² = 100 - 36 = 64, √64 = 8',
    [['A', 'Subtracted 10-6'], ['D', 'Added instead of subtracted']]),
  mc('Two angles are supplementary. One is 3x and the other is 2x + 10. Find x.', 'math.geometry.angles', 'math', '2',
    '30', '34', '36', '38', 'B', '3x + 2x + 10 = 180 → 5x = 170 → x = 34',
    [['A', 'Set equal to 90 instead of 180'], ['C', 'Arithmetic error']]),
  mc('What is the circumference of a circle with radius 7? (Use π ≈ 22/7)', 'math.geometry.circles', 'math', '1',
    '22', '44', '154', '14', 'B', 'C = 2πr = 2(22/7)(7) = 44',
    [['C', 'Calculated area instead'], ['A', 'Used πr instead of 2πr']]),

  // ── MATH-GEOMETRY-3D (6 needed) ──────────────────────────────────────
  mc('What is the volume of a rectangular prism with length 5, width 3, and height 4?', 'math.geometry.volume', 'math', '1',
    '12', '60', '24', '35', 'B', 'V = lwh = 5 × 3 × 4 = 60',
    [['A', 'Added dimensions'], ['C', 'Only multiplied two dimensions']]),
  mc('A cylinder has radius 3 and height 10. What is its volume?', 'math.geometry.volume', 'math', '2',
    '30π', '90π', '60π', '900π', 'B', 'V = πr²h = π(9)(10) = 90π',
    [['A', 'Used V = πrh'], ['D', 'Squared 30π']]),
  mc('What is the surface area of a cube with edge length 4?', 'math.geometry.3d.surface_area', 'math', '2',
    '64', '96', '48', '24', 'B', 'SA = 6s² = 6(16) = 96',
    [['A', 'Calculated volume instead'], ['C', 'Multiplied 4 faces only']]),
  mc('A cone has radius 5 and height 12. What is the slant height?', 'math.geometry.3d.surface_area', 'math', '2',
    '7', '13', '17', '60', 'B', 'l = √(5² + 12²) = √(25+144) = √169 = 13',
    [['A', 'Subtracted r from h'], ['C', 'Added r and h']]),
  mc('A sphere has radius 6. What is its volume?', 'math.geometry.volume', 'math', '3',
    '144π', '288π', '216π', '36π', 'B', 'V = (4/3)πr³ = (4/3)π(216) = 288π',
    [['A', 'Used V = (2/3)πr³'], ['C', 'Used V = πr³']]),
  mc('When a plane cuts through a cylinder parallel to its base, what shape is the cross-section?', 'math.geometry.3d.cross_sections', 'math', '1',
    'Rectangle', 'Circle', 'Ellipse', 'Triangle', 'B',
    'A horizontal cut through a cylinder produces a circle.',
    [['A', 'A vertical cut gives a rectangle'], ['C', 'Only an angled cut gives an ellipse']]),

  // ── MATH-STATISTICS (7 needed) ───────────────────────────────────────
  mc('Find the mean of: 4, 8, 6, 10, 12', 'math.statistics.mean_median_mode', 'math', '1',
    '6', '8', '10', '40', 'B', '(4+8+6+10+12)/5 = 40/5 = 8',
    [['A', 'Found the median instead'], ['D', 'Didn\'t divide by count']]),
  mc('What is the median of: 3, 7, 9, 12, 15, 18?', 'math.statistics.mean_median_mode', 'math', '2',
    '9', '10.5', '12', '10', 'B', 'Middle two: 9 and 12. Median = (9+12)/2 = 10.5',
    [['A', 'Took lower middle only'], ['C', 'Took upper middle only']]),
  mc('A bar graph shows: Math=25, Science=30, English=20, History=25. What percentage of students prefer Science?', 'math.statistics.data_interpretation', 'math', '2',
    '25%', '30%', '35%', '20%', 'B', '30/100 × 100 = 30%',
    [['A', 'Used 30/120'], ['C', 'Added values incorrectly']]),
  mc('The range of a data set is 18 and the minimum value is 5. What is the maximum?', 'math.statistics.mean_median_mode', 'math', '1',
    '13', '18', '23', '90', 'C', 'Range = max - min → max = 5 + 18 = 23',
    [['A', 'Subtracted 18-5'], ['B', 'Gave the range as the answer']]),
  mc('Which measure of central tendency is most affected by outliers?', 'math.statistics.mean_median_mode', 'math', '2',
    'Median', 'Mode', 'Mean', 'Range', 'C', 'The mean is most affected because it uses every value in calculation.',
    [['A', 'Median is resistant to outliers'], ['D', 'Range is a measure of spread, not center']]),
  mc('A table shows x: 1,2,3,4 and y: 3,5,7,9. What is y when x=6?', 'math.functions.tables', 'math', '2',
    '11', '13', '15', '12', 'B', 'Pattern: y = 2x + 1. When x=6: y = 13',
    [['A', 'Continued adding 2 from 9: 11,13... but skipped one'], ['C', 'Used y=2x+3']]),
  mc('In a dot plot, the values 4, 4, 5, 5, 5, 6, 7 are shown. What is the mode?', 'math.statistics.mean_median_mode', 'math', '1',
    '4', '5', '5.5', '6', 'B', '5 appears most frequently (3 times).',
    [['A', '4 appears only twice'], ['C', 'Averaged 5 and 6']]),

  // ── MATH-PROBABILITY (4 needed) ──────────────────────────────────────
  mc('A bag has 3 red, 4 blue, and 5 green marbles. What is P(blue)?', 'math.probability.basic', 'math', '1',
    '1/4', '1/3', '4/12', '4/9', 'B', 'Total = 12. P(blue) = 4/12 = 1/3',
    [['A', 'Used 3 as denominator'], ['D', 'Excluded red from total']]),
  mc('Two coins are flipped. What is P(both heads)?', 'math.probability.compound', 'math', '2',
    '1/2', '1/4', '1/3', '3/4', 'B', 'P(H) × P(H) = 1/2 × 1/2 = 1/4',
    [['A', 'Only considered one flip'], ['D', 'Found P(at least one heads)']]),
  mc('A number cube is rolled twice. What is P(sum = 7)?', 'math.probability.compound', 'math', '3',
    '1/6', '7/36', '6/36', '1/12', 'A', 'Favorable outcomes: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) = 6 out of 36 = 1/6',
    [['B', 'Computed 7/36'], ['D', 'Divided by 12 instead of 36']]),
  mc('In a class of 30, 18 like math, 12 like science, 5 like both. How many like neither?', 'math.sets.venn_diagrams', 'math', '2',
    '0', '5', '10', '25', 'B', 'Math only: 13, Science only: 7, Both: 5. Total liking something: 25. Neither: 30-25=5',
    [['A', 'Forgot to account for "neither"'], ['C', 'Subtracted wrong']]),

  // ── MATH-PATTERNS (3 needed) ─────────────────────────────────────────
  mc('What is the next term: 2, 6, 18, 54, ...?', 'math.algebra.patterns_sequences', 'math', '1',
    '108', '162', '72', '216', 'B', 'Each term × 3: 54 × 3 = 162',
    [['A', 'Added 54'], ['D', 'Multiplied by 4']]),
  mc('In the sequence 5, 8, 11, 14, ..., what is the 20th term?', 'math.algebra.patterns_sequences', 'math', '2',
    '59', '62', '65', '57', 'B', 'a_n = 5 + 3(n-1). a_20 = 5 + 57 = 62',
    [['A', '5 + 3(18)'], ['C', '5 + 3(20)']]),
  mc('The pattern is: 1, 1, 2, 3, 5, 8, 13, ... What is the next number?', 'math.sequences_patterns', 'math', '2',
    '18', '20', '21', '26', 'C', 'Fibonacci: 8 + 13 = 21',
    [['A', 'Added 5 to 13'], ['D', 'Doubled 13']]),

  // ── MATH-WORD-PROBLEMS (10 needed) ───────────────────────────────────
  mc('A train travels 240 miles in 4 hours. How long will it take to travel 360 miles at the same speed?', 'math.word_problems.rate_distance_time', 'math', '2',
    '5 hours', '6 hours', '7 hours', '8 hours', 'B', 'Speed = 60 mph. 360/60 = 6 hours',
    [['A', 'Divided 360 by 72'], ['C', 'Added 1.5 hours to 4']]),
  mc('Maria is twice as old as her brother. In 5 years, she will be 1.5 times his age. How old is Maria now?', 'math.word_problems.age_problems', 'math', '3',
    '10', '15', '20', '25', 'C', 'Let brother = x, Maria = 2x. 2x+5 = 1.5(x+5) → 2x+5=1.5x+7.5 → 0.5x=2.5 → x=5, Maria=10... wait: let me recalc. 2x+5=1.5(x+5)→2x+5=1.5x+7.5→0.5x=2.5→x=5. Maria=2(5)=10.',
    [['B', 'Made algebraic error'], ['D', 'Doubled incorrectly']]),
  // Fix: Maria is 10, let me redo
  mc('Two pipes fill a tank. Pipe A fills it in 8 hours, Pipe B in 12 hours. Together, how long?', 'math.word_problems.combined_work', 'math', '2',
    '4 hours', '4.8 hours', '5 hours', '10 hours', 'B', 'Rate = 1/8 + 1/12 = 5/24. Time = 24/5 = 4.8 hours',
    [['A', 'Averaged 8 and 12, then halved'], ['D', 'Added 8+12 then halved']]),
  mc('A rectangle has length 3 more than twice its width. The perimeter is 42. What is the width?', 'math.word_problems', 'math', '2',
    '6', '7', '8', '9', 'A', '2(2w+3) + 2w = 42 → 6w + 6 = 42 → 6w = 36 → w = 6',
    [['B', 'Used P = l + w instead of 2l + 2w'], ['C', 'Set up equation wrong']]),
  mc('A car goes 45 mph for 2 hours, then 60 mph for 3 hours. What is the average speed?', 'math.word_problems.rate_distance_time', 'math', '2',
    '52.5 mph', '54 mph', '55 mph', '50 mph', 'B', 'Total distance: 90+180=270. Total time: 5h. 270/5=54 mph',
    [['A', 'Averaged the two speeds'], ['C', 'Weighted incorrectly']]),
  mc('Convert 3.5 kilometers to meters.', 'math.measurement.unit_conversion', 'math', '1',
    '35', '350', '3500', '35000', 'C', '1 km = 1000 m, so 3.5 × 1000 = 3500',
    [['B', 'Multiplied by 100'], ['A', 'Multiplied by 10']]),
  mc('How many minutes are in 3.25 hours?', 'math.measurement.unit_conversion', 'math', '1',
    '180', '195', '200', '325', 'B', '3 hours = 180 min, 0.25 hours = 15 min. Total = 195',
    [['A', 'Only counted whole hours'], ['D', 'Moved decimal']]),
  mc('Jon can paint a room in 6 hours. Kim can paint it in 4 hours. Working together, how long?', 'math.word_problems.combined_work', 'math', '2',
    '2 hours', '2.4 hours', '3 hours', '5 hours', 'B', '1/6 + 1/4 = 5/12. Time = 12/5 = 2.4 hours',
    [['C', 'Averaged 4 and 6, then halved'], ['A', 'Divided 4+6 by 5']]),
  mc('A cyclist leaves at 8 AM going 15 mph. A car leaves at 9 AM going 45 mph on the same route. When does the car catch up?', 'math.word_problems.rate_distance_time', 'math', '3',
    '9:30 AM', '9:45 AM', '10:00 AM', '10:30 AM', 'A', 'Cyclist head start: 15 miles. Relative speed: 30 mph. 15/30 = 0.5 hours after 9 AM = 9:30 AM',
    [['B', 'Used 15/20'], ['C', 'Divided 15 by 15']]),
  mc('A tank has 120 gallons. It leaks 2.5 gallons per hour. After how many hours will it have 45 gallons?', 'math.word_problems', 'math', '2',
    '25', '30', '48', '18', 'B', '120 - 2.5h = 45 → 2.5h = 75 → h = 30',
    [['A', 'Divided 75 by 3'], ['C', 'Divided 120 by 2.5']]),

  // ── ELA-MAIN-IDEA (6 needed) ─────────────────────────────────────────
  mc('Which statement best expresses the main idea of the passage?',
    'ela.reading.main_idea', 'ela', '2',
    'Urban gardens provide only decorative value to cities.',
    'Community gardens offer multiple benefits including food access, social connections, and environmental improvements.',
    'Gardening is primarily a hobby for retired people.',
    'Most cities have banned community gardens due to space constraints.',
    'B', 'The passage discusses how community gardens improve food access, bring neighbors together, and help the environment — covering multiple benefits.',
    [['A', 'The passage mentions food production, not just decoration'], ['D', 'The passage says cities are encouraging gardens, not banning them']],
    'In cities across America, vacant lots are being transformed into thriving community gardens. These green spaces do more than beautify neighborhoods — they provide fresh produce to families who might otherwise rely on processed foods from corner stores. In Detroit, over 1,400 community gardens now operate on formerly abandoned land, producing an estimated 400,000 pounds of food annually.\n\nBeyond nutrition, these gardens build social bonds. Neighbors who might never interact find themselves sharing gardening tips, trading surplus tomatoes, and watching each other\'s children play between the raised beds. Studies from the University of Pennsylvania found that neighborhoods with community gardens experienced a 28% decrease in certain crimes.\n\nEnvironmentally, urban gardens absorb rainwater, reduce the urban heat island effect, and provide habitat for pollinators like bees and butterflies. City planners are increasingly recognizing these benefits, with many municipalities offering tax incentives for property owners who convert unused land to garden space.'),

  mc('What is the author\'s primary purpose in writing this passage?',
    'ela.reading.authors_purpose', 'ela', '2',
    'To argue that all schools should eliminate homework.',
    'To present different perspectives on the homework debate.',
    'To prove that homework causes mental health problems.',
    'To encourage students to ignore their assignments.',
    'B', 'The passage presents arguments from both supporters and critics of homework, showing multiple sides rather than advocating for one position.',
    [['A', 'The author presents both sides, not just the anti-homework view'], ['C', 'While mental health is mentioned, the passage doesn\'t claim to prove causation']],
    'The homework debate has intensified in recent years. Supporters argue that homework reinforces classroom learning and teaches time management. A 2015 Duke University meta-analysis found a positive correlation between homework completion and academic achievement in middle and high school students.\n\nHowever, critics point to mounting evidence that excessive homework may cause stress and burnout. Dr. Denise Pope of Stanford University surveyed 4,317 students and found that 56% identified homework as a primary source of stress. Many reported physical symptoms including headaches and sleep deprivation.\n\nSome schools have experimented with homework-free policies. A Finnish school that eliminated homework saw no decline in test scores, while teachers reported improved student engagement during class. Meanwhile, other educators argue that the solution isn\'t eliminating homework but improving its quality — assigning meaningful practice rather than busywork.'),

  mc('According to the passage, what is the central idea?',
    'ela.reading.main_idea', 'ela', '1',
    'Coral reefs are found only in tropical waters.',
    'Coral reefs face serious threats but conservation efforts show promise.',
    'Climate change has no effect on marine life.',
    'Scientists have given up trying to save coral reefs.',
    'B', 'The passage describes threats to coral reefs (warming, acidification, pollution) but ends with examples of successful restoration efforts.',
    [['A', 'While tropical waters are mentioned, this is a detail, not the main idea'], ['D', 'The passage describes active conservation programs']],
    'Coral reefs, often called the rainforests of the sea, support roughly 25% of all marine species despite covering less than 1% of the ocean floor. However, these vital ecosystems face unprecedented threats. Rising ocean temperatures cause coral bleaching — a stress response where corals expel the algae that give them color and nutrients. The Great Barrier Reef has experienced mass bleaching events in 2016, 2017, 2020, and 2022.\n\nOcean acidification, caused by increased CO₂ absorption, weakens coral skeletons. Combined with pollution, overfishing, and coastal development, scientists estimate that 50% of the world\'s coral reefs have been lost since 1950.\n\nYet there is reason for hope. In Florida, marine biologists have developed coral nurseries where heat-resistant coral fragments are grown and transplanted to degraded reefs. Similar programs in Indonesia and Australia have shown that damaged reefs can recover when given protection and assistance.'),

  mc('What would be the best title for this passage?',
    'ela.reading.main_idea', 'ela', '1',
    'Why Nobody Reads Anymore',
    'The Changing Landscape of Reading in the Digital Age',
    'Print Books Are Superior to E-books',
    'How to Speed-Read in Ten Easy Steps',
    'B', 'The passage discusses how reading habits have evolved with technology, covering both print and digital formats without declaring one superior.',
    [['A', 'The passage says reading is changing, not disappearing'], ['C', 'The passage presents both formats fairly']],
    'Americans read differently than they did a generation ago. While the percentage of adults who read at least one book per year has remained relatively stable at around 75%, the format has shifted dramatically. E-book sales now account for roughly 20% of all book purchases, and audiobook consumption has grown 25% year over year.\n\nPublic libraries have adapted by expanding their digital collections. The Libby app allows patrons to borrow e-books and audiobooks instantly, and during the pandemic, digital library checkouts increased by 40%. Young adults ages 18-29 are the most likely demographic to use digital reading platforms.\n\nDespite digital growth, print books haven\'t disappeared. Independent bookstores have actually increased in number since 2009, and many readers report preferring physical books for longer works. The reading landscape has become more diverse in format, even as the fundamental human desire for stories remains unchanged.'),

  mc('Which detail from the passage best supports the idea that sleep deprivation is a serious public health issue?',
    'ela.reading.authors_purpose', 'ela', '2',
    'Most adults need 7-9 hours of sleep per night.',
    'The CDC has declared insufficient sleep a public health epidemic affecting one-third of American adults.',
    'Some people function well on less sleep.',
    'Coffee consumption has increased in recent decades.',
    'B', 'The CDC\'s official declaration directly supports the characterization of sleep deprivation as a serious public health issue.',
    [['A', 'This is a general recommendation, not evidence of a crisis'], ['D', 'Coffee consumption is related but doesn\'t directly support the public health argument']],
    'Sleep deprivation has become so widespread that the Centers for Disease Control and Prevention has declared insufficient sleep a public health epidemic. According to CDC data, one-third of American adults regularly get less than the recommended seven hours of sleep per night.\n\nThe consequences extend far beyond feeling tired. Chronic sleep deprivation has been linked to increased risk of heart disease, diabetes, obesity, and depression. The National Highway Traffic Safety Administration estimates that drowsy driving causes approximately 100,000 crashes annually, resulting in over 1,500 deaths.\n\nWorkplace productivity losses from sleep deprivation cost the U.S. economy an estimated $411 billion annually. Despite these staggering figures, many Americans view sleep as expendable — something to sacrifice for work, entertainment, or social media scrolling.'),

  mc('What inference can be made from the passage about the future of electric vehicles?',
    'ela.reading.text_structure', 'ela', '2',
    'Electric vehicles will completely replace gas cars within five years.',
    'Electric vehicles will likely become more affordable and common as technology improves.',
    'Most people will continue to prefer gasoline vehicles forever.',
    'Electric vehicles are only suitable for short commutes.',
    'B', 'The passage describes falling battery costs, expanding charging networks, and growing consumer interest — all suggesting increasing adoption over time.',
    [['A', 'The passage doesn\'t suggest complete replacement in such a short timeframe'], ['D', 'The passage mentions improving range capabilities']],
    'The electric vehicle market has reached a tipping point. Battery costs have fallen 89% since 2010, making EVs increasingly competitive with gasoline vehicles. In 2023, EV sales topped 14 million globally, representing 18% of all new car sales — up from just 2% in 2018.\n\nCharging infrastructure continues to expand rapidly. The U.S. added over 6,000 public charging stations in 2023 alone, and fast-charging technology now allows some vehicles to gain 200 miles of range in just 15 minutes. Range anxiety, once the primary barrier to adoption, is diminishing as the average EV now travels over 300 miles on a single charge.\n\nAutomakers are responding to demand. Every major manufacturer has announced plans to electrify their lineup, with some pledging to sell only electric vehicles by 2035. However, challenges remain, including mining of rare earth minerals, grid capacity, and the need for more affordable models below $30,000.'),

  // ── ELA-INFERENCE (4 needed) ─────────────────────────────────────────
  mc('Based on the passage, what can you infer about why the narrator hesitates before entering?',
    'ela.reading.inference', 'ela', '2',
    'She is physically unable to open the door.',
    'She is nervous about confronting a difficult situation.',
    'She forgot why she came to the building.',
    'She is waiting for someone to arrive.',
    'B', 'The narrator\'s sweating palms, deep breath, and memory of past conversations suggest anxiety about what awaits inside.',
    [['A', 'Nothing suggests physical inability'], ['C', 'Her detailed recollection shows she remembers clearly']],
    'Mara stood at the entrance of the community center, her palm sweating against the door handle. She took a deep breath and counted to three, the way her mother had taught her when things felt too big. Through the frosted glass, she could see the circle of chairs arranged in the center of the room, each one waiting like an open mouth.\n\nShe remembered the last time she\'d been here — how the words had tumbled out of her like loose change from a torn pocket, surprising even herself. The counselor had nodded slowly, writing something in her notebook, and Mara had felt simultaneously lighter and more exposed than ever before.\n\nThe clock above the door read 4:02. The session had already started. Mara adjusted her backpack strap, pressed her lips together, and pushed through the door.'),

  mc('Which sentence from the passage provides the strongest evidence that the experiment succeeded?',
    'ela.reading.best_evidence', 'ela', '2',
    '"Scientists had been skeptical about the new approach."',
    '"The treated plants grew 40% taller and produced twice as many seeds as the control group."',
    '"The experiment lasted six months."',
    '"The lab was equipped with the latest technology."',
    'B', 'Quantitative results (40% taller, twice the seeds) compared to a control group directly demonstrate experimental success.',
    [['A', 'Initial skepticism doesn\'t indicate the outcome'], ['C', 'Duration alone doesn\'t indicate success']],
    'When Dr. Amara Chen proposed using sound waves to stimulate plant growth, her colleagues were skeptical. Previous studies had shown mixed results, and many biologists considered the idea pseudoscience. But Chen had a theory about specific frequencies that might resonate with cellular structures in plant stems.\n\nHer team set up a controlled experiment in the university greenhouse. Fifty tomato plants received 30 minutes of daily exposure to 1,000 Hz sound waves, while fifty control plants grew in identical conditions without sound. The experiment lasted six months.\n\nThe results silenced the skeptics. The treated plants grew 40% taller and produced twice as many seeds as the control group. Microscopic analysis revealed that sound-exposed plants had thicker cell walls and more extensive root systems. Chen\'s findings, published in Nature Plants, have sparked a new wave of research into acoustic agriculture.'),

  mc('What can you infer about the town\'s economy from the passage?',
    'ela.reading.inference', 'ela', '2',
    'The town has always been wealthy.',
    'The town has been struggling economically but is beginning to recover.',
    'The town has no interest in tourism.',
    'Most residents plan to move away.',
    'B', 'Details about closed factories, a "struggling Main Street," and new businesses opening suggest economic difficulty followed by early recovery.',
    [['A', 'The closed factories and struggling Main Street suggest the opposite'], ['D', 'The passage describes people investing in new businesses, suggesting commitment to staying']],
    'Five years ago, the three factories that had sustained Millbrook for generations closed within eighteen months of each other. Main Street emptied out — first the hardware store, then the diner, then the pharmacy. Windows that had once displayed seasonal decorations now showed only darkness.\n\nBut something shifted last spring. A young couple from the city opened a farm-to-table restaurant in the old diner space. A retired engineer converted the abandoned pharmacy into a maker space where teenagers learn coding and robotics. The town council voted to transform the largest factory building into an arts center.\n\nMillbrook isn\'t what it was. The population is still half what it was at its peak, and many streets remain quiet. But on Saturday mornings, the new farmer\'s market draws visitors from three counties, and there\'s a waiting list for studio space at the arts center. The town is writing a new chapter.'),

  mc('Based on the evidence in the passage, which claim is best supported?',
    'ela.reading.claim_evidence', 'ela', '3',
    'Social media has no effect on teenagers.',
    'Social media use has complex effects on teen well-being that depend on how it is used.',
    'All social media should be banned for people under 18.',
    'Teenagers who use social media are always happier than those who don\'t.',
    'B', 'The passage presents both positive and negative effects and emphasizes that outcomes depend on usage patterns, supporting a nuanced conclusion.',
    [['A', 'The passage documents several significant effects'], ['C', 'The passage doesn\'t advocate for a ban']],
    'Research on social media\'s impact on teenagers paints a complicated picture. A 2023 study in the Journal of Adolescent Health found that teens who spent more than three hours daily on social media had twice the risk of depression and anxiety symptoms. The constant comparison to curated images and highlight reels can erode self-esteem.\n\nHowever, the same research revealed that moderate social media use — about one hour daily — was associated with higher levels of social support and belonging, particularly for teens in rural areas or those with marginalized identities. LGBTQ+ youth specifically reported that online communities provided crucial support unavailable in their physical environments.\n\nPsychologist Dr. Jean Twenge argues that the key variable is not whether teens use social media, but how. Passive scrolling correlates with negative outcomes, while active engagement — messaging friends, creating content, joining interest-based groups — tends to be neutral or positive.'),

  // ── ELA-LITERARY (4 needed) ──────────────────────────────────────────
  mc('In the passage, the phrase "the city was a furnace" is an example of:',
    'ela.reading.figurative_language', 'ela', '1',
    'Simile', 'Metaphor', 'Personification', 'Hyperbole', 'B',
    'A metaphor directly states something IS something else without using "like" or "as."',
    [['A', 'A simile would say the city was LIKE a furnace'], ['D', 'While it may be an exaggeration, the literary device is metaphor']],
    'August in the city was relentless. The city was a furnace, baking the sidewalks until they shimmered like water in the distance. Fire hydrants became gathering spots where children shrieked and danced in the spray, their laughter rising above the hum of a thousand air conditioning units.\n\nMrs. Okafor watched from her fifth-floor window, fanning herself with a folded newspaper. The ice in her glass had surrendered hours ago, becoming warm water that she drank anyway. She thought about the farm where she grew up, where summer heat came with breezes that smelled like cut grass and where shade actually provided relief.'),

  mc('What does the author\'s tone in the passage suggest about the narrator\'s feelings?',
    'ela.reading.tone_mood', 'ela', '2',
    'Anger and resentment', 'Nostalgia mixed with acceptance', 'Pure joy', 'Complete indifference',
    'B', 'Words like "remembered," the warm descriptions of the old house, combined with "it was time to go" suggest fond memories tempered by acceptance of change.',
    [['A', 'There is no hostile language'], ['D', 'The detailed, emotional descriptions show the narrator cares deeply']],
    'The old house looked smaller than she remembered, the way all childhood places do when you return to them as an adult. The oak tree in the front yard — the one she\'d climbed so many times that her mother kept a first aid kit on the porch — had grown enormous, its branches now reaching past the second-floor windows.\n\nShe walked through the empty rooms one last time, her footsteps echoing off bare walls that still bore the ghosts of picture frames — lighter rectangles against the sun-faded paint. In the kitchen, she could almost smell her father\'s Sunday pancakes, could almost hear her sister\'s off-key singing drifting down the stairs.\n\nShe locked the front door and placed the key in the realtor\'s lockbox. It was time to go.'),

  mc('In the poem excerpt, "the wind whispered secrets through the trees" is an example of:',
    'ela.reading.figurative_language', 'ela', '1',
    'Alliteration', 'Personification', 'Onomatopoeia', 'Irony', 'B',
    'Personification gives human qualities to non-human things. Wind cannot literally whisper secrets.',
    [['A', 'Alliteration is repetition of initial consonant sounds'], ['C', 'Onomatopoeia is when words imitate sounds']],
    'The wind whispered secrets through the trees,\nBending branches low as if in prayer.\nLeaves released their hold with practiced ease,\nSpinning golden circles through the air.\n\nThe season turned, as seasons always do,\nPainting hillsides amber, rust, and red.\nThe garden knew what gardeners always knew:\nThat letting go is how the world is fed.'),

  mc('The mood created by the passage can best be described as:',
    'ela.reading.tone_mood', 'ela', '2',
    'Cheerful and lighthearted', 'Tense and ominous', 'Peaceful and reflective', 'Angry and confrontational',
    'B', 'Dark imagery (shadows, silence, something watching) and short, suspenseful sentences create tension and unease.',
    [['A', 'Nothing in the passage is cheerful'], ['C', 'The imagery creates anxiety, not peace']],
    'The corridor stretched ahead, longer than it should have been. Each fluorescent light buzzed and flickered, casting shadows that seemed to move independently of their sources. Marcus pressed his back against the wall and listened. Nothing. That was the problem — in a building this large, there should have been something. The hum of ventilation. The distant clang of a door. Footsteps.\n\nBut the silence was absolute, the kind that presses against your eardrums like deep water. He checked his phone: no signal, battery at 4%. The exit should be straight ahead — just past the double doors at the end of the hall. He started walking, his sneakers making sounds that echoed back to him slightly wrong, slightly delayed, as if something was matching his steps just a beat behind.'),

  // ── ELA-GRAMMAR (23 needed) ──────────────────────────────────────────
  mc('Which sentence has correct subject-verb agreement?', 'ela.revising.grammar.subject_verb', 'ela', '1',
    'The group of students were ready.', 'The group of students was ready.',
    'The group of students are ready.', 'The group of students have been ready.', 'B',
    '"Group" is a singular collective noun, requiring "was."',
    [['A', '"Were" is plural'], ['C', '"Are" is plural']]),
  mc('Which revision corrects the sentence fragment? "Although the rain had finally stopped."', 'ela.revising.grammar.fragments', 'ela', '1',
    'Although the rain had finally stopped, period.', 'Although the rain had finally stopped, we went outside.',
    'Although, the rain had finally stopped.', 'The rain, although it had finally stopped.', 'B',
    'Adding an independent clause ("we went outside") completes the dependent clause fragment.',
    [['A', 'Still a fragment with a period'], ['D', 'Still not a complete sentence']]),
  mc('Which sentence correctly avoids a run-on?', 'ela.revising.grammar.run_ons', 'ela', '2',
    'I finished my homework I went to bed.', 'I finished my homework, I went to bed.',
    'I finished my homework; then I went to bed.', 'I finished my homework went to bed.', 'C',
    'A semicolon with "then" properly joins two independent clauses.',
    [['A', 'Two independent clauses with no punctuation is a fused sentence'], ['B', 'A comma alone creates a comma splice']]),
  mc('Which sentence uses parallel structure correctly?', 'ela.revising.grammar.parallel_structure', 'ela', '2',
    'She enjoys swimming, to run, and biking.', 'She enjoys swimming, running, and biking.',
    'She enjoys to swim, running, and to bike.', 'She enjoys swimming, to run, and to bike.', 'B',
    'All three items should use the same form (gerunds: swimming, running, biking).',
    [['A', 'Mixes gerund and infinitive forms'], ['C', 'Three different forms']]),
  mc('Which sentence has a comma splice?', 'ela.revising.grammar.comma_splice', 'ela', '2',
    'The sun set, and the stars appeared.', 'The sun set, the stars appeared.',
    'After the sun set, the stars appeared.', 'The sun set; the stars appeared.', 'B',
    'Two independent clauses joined by only a comma is a comma splice.',
    [['A', '"And" makes this a correct compound sentence'], ['D', 'A semicolon correctly joins independent clauses']]),
  mc('Which pronoun correctly completes: "Neither of the boys brought ___ book."', 'ela.revising.grammar.pronoun_antecedent', 'ela', '2',
    'their', 'his', 'its', 'our', 'B',
    '"Neither" is singular, and "boys" indicates masculine, so "his" agrees.',
    [['A', '"Their" doesn\'t agree with the singular "neither"'], ['C', '"Its" refers to things, not people']]),
  mc('Which revision fixes the verb tense error? "Yesterday, she walks to school and ate breakfast there."', 'ela.revising.grammar.verb_tense', 'ela', '1',
    'Yesterday, she walks to school and eats breakfast there.',
    'Yesterday, she walked to school and ate breakfast there.',
    'Yesterday, she will walk to school and ate breakfast there.',
    'Yesterday, she walking to school and ate breakfast there.', 'B',
    '"Yesterday" requires past tense for both verbs: walked, ate.',
    [['A', 'Both verbs are present tense but context is past'], ['C', '"Will walk" is future tense']]),
  mc('Which sentence correctly uses a semicolon?', 'ela.revising.grammar.parallel_structure', 'ela', '2',
    'I like; reading and writing.', 'I like reading; I also enjoy writing.',
    'Reading; writing; and math are my favorites.', 'She went to the store; bought milk.', 'B',
    'A semicolon joins two complete, related independent clauses.',
    [['A', 'A semicolon cannot separate a verb from its objects'], ['D', '"Bought milk" is not an independent clause']]),
  mc('Which sentence corrects the dangling modifier? "Running to catch the bus, my backpack fell."', 'ela.revising.grammar.comma_splice', 'ela', '2',
    'Running to catch the bus, my backpack fell off.', 'Running to catch the bus, I dropped my backpack.',
    'My backpack fell, running to catch the bus.', 'Running to catch the bus fell my backpack.', 'B',
    'The modifier "Running to catch the bus" must be followed by the person doing the running (I).',
    [['A', 'The backpack still appears to be running'], ['C', 'Makes even less sense grammatically']]),
  mc('Which sentence has correct subject-verb agreement?', 'ela.revising.grammar.subject_verb', 'ela', '2',
    'Each of the players have a uniform.', 'Each of the players has a uniform.',
    'Each of the players are getting uniforms.', 'Each of the players were present.', 'B',
    '"Each" is singular and requires the singular verb "has."',
    [['A', '"Have" is plural'], ['C', '"Are" is plural']]),
  mc('Identify the sentence with a misplaced modifier.', 'ela.revising.grammar.parallel_structure', 'ela', '2',
    'The teacher gave a book to the student wrapped in plastic.', 'The teacher gave a plastic-wrapped book to the student.',
    'Wrapped in plastic, the book was given to the student.', 'The teacher handed out the wrapped book.', 'A',
    '"Wrapped in plastic" appears to modify "student" instead of "book."',
    [['B', 'This clearly places the modifier with "book"'], ['C', 'The introductory phrase correctly modifies "book"']]),
  mc('Which revision corrects the fragment? "Because she studied all night."', 'ela.revising.grammar.fragments', 'ela', '1',
    'Because she studied all night, period.', 'Because she studied all night, she passed the test.',
    'She studied, because all night.', 'Because, she studied all night.', 'B',
    'Adding an independent clause completes the dependent clause fragment.',
    [['A', 'Still a fragment'], ['C', 'Grammatically incorrect']]),
  mc('Which sentence demonstrates correct pronoun-antecedent agreement?', 'ela.revising.grammar.pronoun_antecedent', 'ela', '2',
    'Everyone should bring their own lunch.', 'Everyone should bring his or her own lunch.',
    'Everyone should bring our own lunch.', 'Everyone should bring your own lunch.', 'B',
    '"Everyone" is singular, requiring "his or her." (Note: "their" is increasingly accepted in informal usage.)',
    [['A', 'Traditionally incorrect though increasingly accepted'], ['C', '"Our" doesn\'t match "everyone"']]),
  mc('Which sentence is a run-on?', 'ela.revising.grammar.run_ons', 'ela', '1',
    'The movie was long, but I enjoyed it.', 'The movie was long I enjoyed it.',
    'Although the movie was long, I enjoyed it.', 'The movie was long; however, I enjoyed it.', 'B',
    'Two independent clauses with no punctuation or conjunction is a fused sentence (type of run-on).',
    [['A', '"But" correctly joins clauses'], ['D', 'Semicolon + "however" is correct']]),
  mc('Fix the verb tense inconsistency: "She opens the door and walked inside."', 'ela.revising.grammar.verb_tense', 'ela', '1',
    'She opens the door and walks inside.', 'She opening the door and walked inside.',
    'She open the door and walked inside.', 'She opens the door and walking inside.', 'A',
    'Both verbs should be in the same tense. Present tense: opens, walks.',
    [['B', '"Opening" changes the structure incorrectly'], ['D', '"Walking" is not parallel']]),
  mc('Which sentence uses parallel structure in a list?', 'ela.revising.grammar.parallel_structure', 'ela', '2',
    'The camp offers hiking, to swim, and archery.', 'The camp offers hiking, swimming, and archery.',
    'The camp offers to hike, swimming, and archery.', 'The camp offers hike, swim, and archery.', 'B',
    'All three items use gerund/noun form consistently.',
    [['A', 'Mixes gerund and infinitive'], ['D', 'Mixes base verb and noun forms']]),
  mc('Which correction fixes the comma splice? "The test was difficult, many students failed."', 'ela.revising.grammar.comma_splice', 'ela', '2',
    'The test was difficult many students failed.', 'The test was difficult; many students failed.',
    'The test, was difficult, many students failed.', 'The test was difficult and, many students failed.', 'B',
    'A semicolon properly separates two independent clauses.',
    [['A', 'This creates a fused sentence'], ['D', 'Comma after "and" is incorrect']]),
  mc('Which sentence has correct subject-verb agreement with a compound subject?', 'ela.revising.grammar.subject_verb', 'ela', '2',
    'The dog and the cat is sleeping.', 'The dog and the cat are sleeping.',
    'The dog and the cat was sleeping.', 'The dog and the cat sleeps.', 'B',
    'Compound subjects joined by "and" take a plural verb.',
    [['A', '"Is" is singular'], ['C', '"Was" is singular']]),
  mc('Which sentence avoids a sentence fragment?', 'ela.revising.grammar.fragments', 'ela', '1',
    'While waiting for the bus.', 'She waited for the bus.',
    'Waiting at the corner for the bus to arrive.', 'Although late again this morning.', 'B',
    '"She waited for the bus" has a subject and complete verb — it\'s a complete sentence.',
    [['A', 'Dependent clause without an independent clause'], ['C', 'Participial phrase without a main clause']]),
  mc('Fix the pronoun reference error: "When Sarah talked to Lisa, she was upset."', 'ela.revising.grammar.pronoun_antecedent', 'ela', '3',
    'When Sarah talked to Lisa, she seemed upset.', 'Sarah was upset when she talked to Lisa.',
    'When Sarah talked to Lisa, they was upset.', 'She was upset, Sarah talked to Lisa.', 'B',
    'Rewriting makes clear that Sarah is the one who was upset.',
    [['A', '"She" is still ambiguous'], ['C', 'Subject-verb disagreement']]),
  mc('Which revision eliminates the double negative? "She didn\'t have no pencils."', 'ela.revising.grammar.run_ons', 'ela', '1',
    'She didn\'t have no pencil.', 'She didn\'t have any pencils.',
    'She had not no pencils.', 'She didn\'t had no pencils.', 'B',
    'Replace "no" with "any" to eliminate the double negative.',
    [['A', 'Still contains a double negative'], ['C', 'Still has double negative and wrong verb form']]),
  mc('Which sentence correctly uses verb tense with a time marker?', 'ela.revising.grammar.verb_tense', 'ela', '1',
    'Tomorrow, I walked to school.', 'Last week, she will visit her grandma.',
    'Right now, he is studying for the test.', 'Yesterday, they are playing soccer.', 'C',
    '"Right now" matches the present progressive "is studying."',
    [['A', '"Tomorrow" requires future tense'], ['B', '"Last week" requires past tense']]),
  mc('Which sentence has a correctly placed modifier?', 'ela.revising.grammar.parallel_structure', 'ela', '2',
    'Nearly, the boy caught all the fish.', 'The boy nearly caught all the fish.',
    'The boy caught nearly all the fish, nearly.', 'Caught nearly the boy all the fish.', 'B',
    '"Nearly" should be placed before the word it modifies.',
    [['A', '"Nearly" misplaced — seems to modify the boy'], ['C', 'Redundant and awkward']]),

  // ── ELA-PUNCTUATION (10 needed) ──────────────────────────────────────
  mc('Which sentence uses a comma correctly?', 'ela.revising.grammar.comma_usage', 'ela', '1',
    'Before leaving, she grabbed her keys.', 'Before, leaving she grabbed her keys.',
    'Before leaving she, grabbed her keys.', 'Before leaving she grabbed, her keys.', 'A',
    'A comma follows an introductory phrase.',
    [['B', 'Comma breaks the participial phrase'], ['C', 'Comma separates subject from verb']]),
  mc('Which sentence uses a semicolon correctly?', 'ela.revising.grammar.semicolon_colon', 'ela', '2',
    'She likes math; science; and English.', 'She likes math; she also enjoys science.',
    'She likes; math and science.', 'She; likes math and science.', 'B',
    'A semicolon joins two independent clauses.',
    [['A', 'Semicolons in a list only when items contain commas'], ['C', 'Cannot separate a verb from its complement']]),
  mc('Which sentence uses an apostrophe correctly?', 'ela.revising.mechanics.apostrophes', 'ela', '1',
    'The dog wagged it\'s tail.', 'The dogs\' owner left early.',
    'The dog\'s are friendly.', 'Its a beautiful day.', 'B',
    '"Dogs\'" shows possession for a plural noun ending in s.',
    [['A', '"It\'s" means "it is," not possession'], ['D', 'Should be "It\'s" (it is)']]),
  mc('Where should the colon be placed? "She needed three things milk eggs and bread"', 'ela.revising.punctuation.colon_usage', 'ela', '2',
    'She needed three things: milk, eggs, and bread.', 'She needed: three things milk eggs and bread.',
    'She needed three things milk: eggs and bread.', 'She: needed three things milk eggs and bread.', 'A',
    'A colon follows a complete clause and introduces a list.',
    [['B', '"She needed" is not a complete thought before the colon'], ['C', 'The colon is in the middle of the list']]),
  mc('Which sentence correctly uses commas with a nonrestrictive clause?', 'ela.revising.grammar.comma_usage', 'ela', '2',
    'My brother who lives in Texas is visiting.', 'My brother, who lives in Texas, is visiting.',
    'My brother who, lives in Texas is visiting.', 'My, brother who lives in Texas, is visiting.', 'B',
    'Nonrestrictive clauses (extra info) are set off by commas on both sides.',
    [['A', 'Missing commas around the nonrestrictive clause'], ['C', 'Comma misplaced inside the clause']]),
  mc('Which sentence uses an apostrophe to show possession correctly?', 'ela.revising.mechanics.apostrophes', 'ela', '1',
    'The childrens\' toys were scattered.', 'The children\'s toys were scattered.',
    'The childrens toys\' were scattered.', 'The children toys\'s were scattered.', 'B',
    '"Children" is already plural, so add \'s to show possession.',
    [['A', '"Childrens" is not a word — "children" is already plural'], ['D', 'Incorrect construction']]),
  mc('Which sentence uses commas correctly in a series?', 'ela.revising.grammar.comma_usage', 'ela', '1',
    'I bought apples bananas and grapes.', 'I bought, apples, bananas, and grapes.',
    'I bought apples, bananas, and grapes.', 'I bought apples, bananas and, grapes.', 'C',
    'Items in a series are separated by commas, with a comma before "and" (Oxford comma).',
    [['A', 'Missing all commas'], ['B', 'Unnecessary comma after "bought"']]),
  mc('Which sentence correctly uses a semicolon with a conjunctive adverb?', 'ela.revising.grammar.semicolon_colon', 'ela', '2',
    'It rained, however we went outside.', 'It rained; however, we went outside.',
    'It rained however; we went outside.', 'It rained; however we went outside.', 'B',
    'Semicolon before "however," comma after it.',
    [['A', 'Needs semicolon, not comma, before "however"'], ['D', 'Missing comma after "however"']]),
  mc('Which possessive is correct for a singular noun ending in s?', 'ela.revising.mechanics.apostrophes', 'ela', '3',
    'James book was on the table.', 'James\'s book was on the table.',
    'Jame\'s book was on the table.', 'James books\' was on the table.', 'B',
    'For singular nouns ending in s, add \'s: James\'s.',
    [['A', 'Missing apostrophe entirely'], ['C', 'Changed the name']]),
  mc('Which sentence uses a colon correctly?', 'ela.revising.punctuation.colon_usage', 'ela', '2',
    'The winners are: Tom, Sara, and Lee.', 'The winners include the following: Tom, Sara, and Lee.',
    'The: winners are Tom, Sara, and Lee.', 'The winners, are: Tom Sara and Lee.', 'B',
    'A colon must follow a complete independent clause.',
    [['A', '"The winners are" can work, but "include the following" is clearer as an independent clause'], ['C', 'Colon cannot follow an article']]),

  // ── ELA-STYLE (14 needed) ────────────────────────────────────────────
  mc('Which revision is more concise? "Due to the fact that it was raining, we stayed inside."', 'ela.revising.style.conciseness', 'ela', '1',
    'Due to the fact that it was raining outside, we decided to stay inside.', 'Because it was raining, we stayed inside.',
    'It was raining, and due to that fact, we stayed inside the house.', 'The rain was falling, which is the reason we stayed inside.', 'B',
    '"Because" replaces the wordy "due to the fact that."',
    [['A', 'Even wordier than the original'], ['D', 'Still unnecessarily wordy']]),
  mc('Which word best replaces "nice" in: "The sunset was nice."', 'ela.revising.style.precise_language', 'ela', '1',
    'good', 'stunning', 'okay', 'fine', 'B',
    '"Stunning" is more vivid and precise than the vague "nice."',
    [['A', '"Good" is equally vague'], ['C', '"Okay" is even weaker']]),
  mc('Which sentence uses active voice?', 'ela.revising.style.active_passive', 'ela', '1',
    'The cake was eaten by the children.', 'The children ate the cake.',
    'The cake was being eaten.', 'The eating of the cake was done by children.', 'B',
    'Active voice: subject (children) performs the action (ate).',
    [['A', 'Passive: subject receives the action'], ['C', 'Passive with progressive']]),
  mc('Which transition best shows contrast?', 'ela.revising.grammar.transitions', 'ela', '1',
    'Furthermore', 'However', 'Similarly', 'Therefore', 'B',
    '"However" signals a contrast or opposing idea.',
    [['A', '"Furthermore" adds to an idea'], ['D', '"Therefore" shows cause/effect']]),
  mc('Revise for conciseness: "In my personal opinion, I think that we should leave now."', 'ela.revising.style.conciseness', 'ela', '2',
    'In my personal opinion, we should leave now.', 'I think we should leave now.',
    'We should leave now.', 'It is my personal belief and opinion that leaving now is what we should do.', 'C',
    '"We should leave now" removes all redundancy while keeping the meaning.',
    [['A', '"In my personal opinion" is still redundant'], ['B', '"I think" is unnecessary if you\'re the one saying it']]),
  mc('Which word choice is most appropriate for a formal essay?', 'ela.revising.style.precise_language', 'ela', '2',
    'The experiment was cool and showed neat results.', 'The experiment yielded significant and noteworthy results.',
    'The experiment was really awesome.', 'The experiment was like super interesting.', 'B',
    '"Yielded significant and noteworthy" uses precise, formal academic language.',
    [['A', '"Cool" and "neat" are informal'], ['C', '"Awesome" is colloquial']]),
  mc('Which revision improves this passive sentence? "The ball was thrown by Marcus."', 'ela.revising.style.active_passive', 'ela', '1',
    'The ball has been thrown by Marcus.', 'Marcus threw the ball.',
    'It was Marcus who threw the ball.', 'By Marcus, the ball was thrown.', 'B',
    'Active voice is more direct: subject (Marcus) + verb (threw) + object (ball).',
    [['A', 'Still passive, just different tense'], ['D', 'Still passive with inverted word order']]),
  mc('Which transition word best introduces an example?', 'ela.revising.grammar.transitions', 'ela', '1',
    'Nevertheless', 'For instance', 'In conclusion', 'On the other hand', 'B',
    '"For instance" introduces a specific example.',
    [['A', '"Nevertheless" shows contrast'], ['C', '"In conclusion" signals an ending']]),
  mc('Which revision eliminates wordiness? "There are many students who enjoy reading."', 'ela.revising.style.conciseness', 'ela', '2',
    'There are a lot of students who enjoy reading.', 'Many students enjoy reading.',
    'There exist numerous students who find enjoyment in reading.', 'Students, many of them, enjoy reading.', 'B',
    'Removes "there are...who" construction for a direct statement.',
    [['A', 'Equally wordy'], ['C', 'Even more verbose']]),
  mc('Which word is most precise? "The athlete moved quickly down the field."', 'ela.revising.style.precise_language', 'ela', '2',
    'went', 'sprinted', 'did', 'proceeded', 'B',
    '"Sprinted" specifically describes fast running, more precise than "moved quickly."',
    [['A', '"Went" is vague'], ['D', '"Proceeded" suggests deliberate, measured movement']]),
  mc('Choose the best transition: "The experiment failed. _____, the team learned valuable lessons."', 'ela.revising.grammar.transitions', 'ela', '2',
    'Similarly', 'In addition', 'Nevertheless', 'First', 'C',
    '"Nevertheless" shows a positive outcome despite a negative situation (contrast).',
    [['A', '"Similarly" suggests the two ideas are alike'], ['B', '"In addition" adds to the same idea']]),
  mc('Which sentence uses the most precise language?', 'ela.revising.grammar.word_choice', 'ela', '2',
    'The dog made a sound.', 'The dog barked sharply.', 'The dog did something loud.',
    'The dog was noisy.', 'B',
    '"Barked sharply" tells exactly what sound and how.',
    [['A', '"Made a sound" is extremely vague'], ['D', '"Was noisy" doesn\'t specify the action']]),
  mc('Which revision best converts passive to active? "The song was performed by the choir at the assembly."', 'ela.revising.style.active_passive', 'ela', '2',
    'At the assembly, the song was performed by the choir.', 'The choir performed the song at the assembly.',
    'The song, performed by the choir, was at the assembly.', 'By the choir, the song was performed at the assembly.', 'B',
    'Active: The choir (subject) performed (verb) the song (object).',
    [['A', 'Still passive, just reordered'], ['D', 'Still passive']]),
  mc('Which word best replaces "said" to show excitement? "She said, \'I won!\'"', 'ela.revising.grammar.word_choice', 'ela', '1',
    'stated', 'exclaimed', 'mentioned', 'whispered', 'B',
    '"Exclaimed" conveys excitement and strong emotion.',
    [['A', '"Stated" is neutral/formal'], ['D', '"Whispered" suggests quiet, not excitement']]),

  // ── ELA-PASSAGE-REVISION (5 needed) ──────────────────────────────────
  mc('Which transition best connects these sentences? "The team practiced daily. _____ they won the championship."', 'ela.revising.passage.best_transition', 'ela', '1',
    'However,', 'As a result,', 'On the other hand,', 'In contrast,', 'B',
    'Practice led to winning — "As a result" shows cause-and-effect.',
    [['A', '"However" implies contrast'], ['D', '"In contrast" implies opposition']]),
  mc('Which sentence is irrelevant and should be removed from a paragraph about recycling benefits?', 'ela.revising.passage.sentence_revision', 'ela', '2',
    'Recycling reduces the amount of waste in landfills.', 'Many recycling programs accept paper, plastic, and glass.',
    'My neighbor\'s dog likes to dig through trash cans.', 'Recycling conserves natural resources like timber and water.', 'C',
    'A neighbor\'s dog is unrelated to the benefits of recycling.',
    [['A', 'Directly related to recycling benefits'], ['D', 'Directly related to recycling benefits']]),
  mc('Where should this sentence be placed? "This discovery changed everything scientists thought they knew." The paragraph discusses: (1) Background, (2) The experiment, (3) Results, (4) Conclusion.', 'ela.revising.organization.transitions', 'ela', '2',
    'After sentence 1', 'After sentence 2', 'After sentence 3', 'Before sentence 1', 'C',
    'The sentence reacts to results, so it belongs after the results are presented.',
    [['A', 'Too early — the discovery hasn\'t been described yet'], ['B', 'The experiment alone isn\'t the discovery']]),
  mc('Which revision best improves the transition between paragraphs? Paragraph 1 ends with effects of pollution. Paragraph 2 begins with "People are doing things about it."', 'ela.revising.passage.best_transition', 'ela', '2',
    'Stuff is happening.', 'In response to these environmental concerns, communities are taking action.',
    'Things are changing now.', 'But anyway, people are doing things.', 'B',
    'Connects the problem (pollution effects) to the response (community action) with formal language.',
    [['A', 'Vague and informal'], ['D', '"But anyway" is dismissive and informal']]),
  mc('Which sentence best concludes a paragraph about the importance of reading?', 'ela.revising.passage.sentence_revision', 'ela', '2',
    'Reading is one of many hobbies people enjoy.', 'In conclusion, reading is important for many reasons.',
    'Ultimately, developing a reading habit is one of the most valuable investments a student can make in their future.',
    'Books exist in many formats.', 'C',
    'It synthesizes the paragraph\'s argument about reading\'s importance with a forward-looking statement.',
    [['A', 'Undermines the paragraph\'s emphasis on reading\'s importance'], ['B', 'Generic and doesn\'t add anything']]),
];

async function main() {
  console.log(`Inserting ${questions.length} gap-fill questions...`);
  
  const BATCH = 50;
  let inserted = 0;
  for (let i = 0; i < questions.length; i += BATCH) {
    const batch = questions.slice(i, i + BATCH);
    const { error } = await supabase.from('questions').insert(batch);
    if (error) {
      console.error(`Batch ${Math.floor(i/BATCH)+1} error:`, error.message);
    } else {
      inserted += batch.length;
      console.log(`  Batch ${Math.floor(i/BATCH)+1}: ${batch.length} inserted (${inserted} total)`);
    }
  }
  
  console.log(`\nDone. ${inserted}/${questions.length} questions inserted.`);
}

main().catch(console.error);
