import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const outDir = resolve(__dirname, '..', 'content', 'questions');

interface Q {
  section: string; category: string; difficulty: number; type: string;
  stem: string; stimulus?: string; options: { label: string; text: string }[];
  correctAnswer: string; explanation: string;
  commonMistakes: { label: string; explanation: string }[];
  skills: string[]; tags: string[];
}

function mk(cat: string, diff: number, stem: string, a: string, b: string, c: string, d: string, exp: string, stim: string): Q {
  return {
    section: 'ela', category: cat, difficulty: diff, type: 'multiple_choice',
    stem, stimulus: stim,
    options: [{label:'A',text:a},{label:'B',text:b},{label:'C',text:c},{label:'D',text:d}],
    correctAnswer: 'A', explanation: exp,
    commonMistakes: [{label:'B',explanation:'Not supported by the passage'},{label:'C',explanation:'Too narrow or specific'}],
    skills: ['reading-comprehension'], tags: ['reading'],
  };
}

// Main idea: need 2 more
const mi: Q[] = [
  mk('ela.reading.main_idea', 2, 'What is the main idea of this passage?',
    'Renewable energy adoption is accelerating globally but faces infrastructure challenges.',
    'Solar panels are the best energy source.', 'Fossil fuels will never be replaced.', 'Wind energy is too expensive.',
    'The passage discusses growth in renewables and the challenges of grid modernization.',
    `Global renewable energy capacity grew by 50% in 2023, the fastest pace in two decades. Solar power led the expansion, with costs falling 90% since 2010, making it cheaper than coal in most markets. Wind energy also grew substantially, with offshore installations doubling. China accounted for half of all new renewable capacity, though the United States and Europe also made significant gains. Despite this progress, challenges remain. Electricity grids designed for centralized fossil fuel plants must be modernized to handle distributed, intermittent renewable sources. Energy storage technology, while improving rapidly, cannot yet cost-effectively store power at the scale needed for fully renewable grids. Experts emphasize that the transition is inevitable but warn that without massive investment in grid infrastructure, the pace of change may slow.`),
  mk('ela.reading.text_structure', 1, 'How is this passage organized?',
    'Description of a phenomenon followed by its scientific explanation',
    'Chronological narrative', 'Persuasive argument', 'Compare and contrast',
    'The passage first describes the Northern Lights, then explains the science behind them.',
    `The Northern Lights, or aurora borealis, are one of nature's most spectacular displays—shimmering curtains of green, purple, and pink light dancing across the polar sky. For centuries, cultures across the Arctic attributed the lights to supernatural causes: the Norse believed they were reflections from the armor of the Valkyries, while the Inuit saw them as spirits playing ball with a walrus skull. The scientific explanation, while less romantic, is equally remarkable. Charged particles from the sun, carried by solar wind, collide with gas molecules in Earth's upper atmosphere. These collisions excite the molecules, causing them to emit photons of light. The color depends on which gas is struck: oxygen produces green and red, while nitrogen creates blue and purple. The displays are most common near the magnetic poles, where Earth's magnetic field funnels the charged particles toward the atmosphere.`),
];

// Inference: need 13 more
const inf: Q[] = [
  mk('ela.reading.inference', 2, 'What can you infer about the character\'s past?',
    'She grew up in poverty and is determined to provide better for her own children.',
    'She has always been wealthy.', 'She doesn\'t care about money.', 'She grew up in the suburbs.',
    'Counting items at checkout and her childhood memories suggest past financial hardship.',
    `Mrs. Chen counted the items in her grocery cart twice before approaching the checkout. Old habits. There was a time when she would put things back—the name-brand cereal, the fresh strawberries, the good orange juice—replacing them with their cheaper, sadder alternatives. That time was fifteen years ago, when she was working two jobs and feeding two kids on what barely covered one. Now she could buy the strawberries without checking the price, but she still checked. Her daughter, Sophie, tossed a bag of organic granola into the cart without looking at the label. Mrs. Chen didn't say anything. This was the whole point, wasn't it? So that Sophie would never have to count.`),
  mk('ela.reading.inference', 3, 'What does this passage imply about the nature of courage?',
    'True courage involves acting despite fear, not the absence of fear.',
    'Courageous people never feel afraid.', 'Only soldiers are brave.', 'Fear is a weakness.',
    'The firefighter\'s admission of fear alongside his continued action redefines courage.',
    `The journalist asked the firefighter the question everyone asks: "Weren't you scared?" Captain Rodriguez set down his coffee and considered. "Every single time," he said. "Twenty-three years, and I'm scared every single time I walk into a burning building." The journalist seemed surprised. She had expected bravado, the tough-guy answer. Instead, Rodriguez described the exact moment fear hits—standing at the threshold, heat pressing against the faceplate, the sound of a structure groaning under its own weight. "The recruits think courage means not being afraid," he continued. "I spend a lot of time un-teaching that. Courage means your hands are shaking and you go in anyway, because someone in there needs you more than you need to be comfortable."`),
  mk('ela.reading.best_evidence', 1, 'Which detail best supports the idea that the program made a difference?',
    '"Graduation rates at participating schools increased from 64% to 89% over five years."',
    '"The program was funded by a local nonprofit."', '"Mentors met with students weekly."', '"The program started in 2015."',
    'The graduation rate increase provides the most concrete, measurable evidence of impact.',
    'Describes funding, not outcomes', 'Describes structure, not results',
    ['reading-comprehension'], ['best-evidence'],
    `The mentorship program paired at-risk high school students with adult volunteers from the community. Mentors met with students weekly—sometimes at school, sometimes at coffee shops or community centers—for conversations that ranged from homework help to career planning to simply having someone who listened. The program was funded by a local nonprofit and started in 2015 with just twelve mentor pairs. By 2020, it had expanded to over 200. Graduation rates at participating schools increased from 64% to 89% over five years. More striking were the qualitative changes: students reported feeling more hopeful about their futures, and several credited their mentors with being the first adults outside their families to believe in them.`),
  mk('ela.reading.inference', 1, 'What can you infer about why the character collects maps?',
    'Maps represent the adventures and freedom she dreams about but hasn\'t yet experienced.',
    'She is a professional cartographer.', 'She gets lost frequently.', 'Maps are expensive and she collects valuables.',
    'Tracing routes to places she\'s never been and wanting to "go everywhere" suggest unfulfilled wanderlust.',
    'No evidence of this profession', 'The passage suggests dreams, not practical use',
    ['reading-comprehension', 'inference'], ['inference'],
    `Lila's bedroom walls were covered in maps. Not posters—actual maps, bought from thrift stores and antique shops and the estate sales she dragged her mother to on Saturday mornings. She had a 1962 road atlas of the United States, a hand-drawn map of the London Underground from the 1940s, and a nautical chart of the Caribbean that smelled like salt and old paper. She had never been outside of Ohio. But every night before sleep, she would trace the routes with her finger—down Highway 1 along the California coast, across the Channel to France, through the winding streets of Tokyo. "Where do you want to go?" her mother once asked. Lila didn't hesitate. "Everywhere." She said it the way some people say "I love you"—like it was the truest thing she knew.`),
  mk('ela.reading.claim_evidence', 2, 'What claim does this passage support?',
    'Restorative justice practices can be more effective than punitive discipline in schools.',
    'Students should never face consequences.', 'Suspension is always the best approach.', 'Only elementary schools need discipline reform.',
    'The comparison of outcomes before and after implementation supports restorative justice effectiveness.',
    'The passage describes accountability, not lack of consequences', 'The passage provides evidence against this',
    ['reading-comprehension'], ['claim-evidence'],
    `When Oakland Unified School District replaced traditional suspensions with restorative justice practices, critics predicted chaos. Instead, the opposite happened. Suspensions dropped by 87%. Chronic absenteeism decreased by 24%. And—crucially—academic achievement improved. The restorative approach doesn't eliminate consequences for misbehavior. Instead of removing students from the learning environment, it brings together the offending student, affected parties, and a trained facilitator in a structured dialogue called a "circle." Students must face the people they've harmed, listen to the impact of their actions, and develop a plan to repair the damage. The process is often harder than sitting in a suspension room. "Suspension was easy," said one student. "I just stayed home and played video games. In a circle, I had to look my teacher in the eye and explain why I disrespected her. That was way harder—and it actually changed how I act."`),
  mk('ela.reading.inference', 2, 'What can you infer about the grandmother\'s philosophy of life?',
    'She believes in finding joy in simple, everyday moments rather than grand achievements.',
    'She values wealth above all else.', 'She thinks life is meaningless.', 'She believes only big events matter.',
    'Celebrating small moments and her sayings show a philosophy of everyday joy.',
    'She finds great meaning in simple things', 'Her attitude is opposite—every small moment counts',
    ['reading-comprehension', 'inference'], ['inference'],
    `Grandmother celebrated everything. Not just birthdays and holidays—she celebrated Tuesdays, the first tomato from the garden, a particularly good sunset, the sound of rain on the tin roof. "Another gift," she would say, pouring her morning coffee as if the beans had been personally delivered by angels. She kept a journal she called her "gratitude book," and every night she wrote three things that had made the day worth living. Most entries were absurdly mundane: "The butter was soft enough to spread." "Heard a mockingbird sing four different songs." "The crossword puzzle in Wednesday's paper was very satisfying." When I asked her once if she had any regrets, she looked confused. "About what?" she said. "Look at this orange. Have you ever really looked at an orange? It's remarkable." She held it up to the window, turning it in the light, and I swear for a moment it was.`),
  mk('ela.reading.inference', 3, 'What does this passage suggest about the narrator\'s relationship with her identity?',
    'She is learning to embrace a complex, multicultural identity rather than choosing one side.',
    'She rejects both cultures.', 'She fully identifies as American.', 'She fully identifies as Korean.',
    'The metaphor of being a bridge and the final acceptance suggest embracing dual identity.',
    'She embraces both cultures', 'She describes being between two worlds',
    ['reading-comprehension', 'inference'], ['inference'],
    `At home, I am Korean. I take off my shoes at the door, eat rice at every meal, and call my elders "auntie" and "uncle" even when they are neither. At school, I am American. I eat pizza in the cafeteria, debate in English class, and listen to music my grandmother would not understand. For years, I felt like a mistranslation—never quite right in either language. At Korean school on Saturdays, the other kids said my Korean was "too American." At regular school on weekdays, classmates asked where I was "really" from. I spent my childhood feeling like a bridge between two countries, which sounds poetic until you realize that bridges belong to neither side. It wasn't until college, surrounded by other hyphenated Americans, that I understood: the bridge itself is the identity. I am not half of two things. I am wholly, completely, both.`),
  mk('ela.reading.best_evidence', 3, 'Which sentence best supports the claim that the author values process over product?',
    '"The painting I am most proud of is one I never finished."',
    '"She studied art for four years."', '"Her studio was well-organized."', '"She used expensive paints."',
    'Valuing an unfinished painting directly demonstrates prioritizing the creative process.',
    'Education doesn\'t indicate process vs product values', 'Organization is about workspace, not artistic philosophy',
    ['reading-comprehension'], ['best-evidence'],
    `I have been painting for thirty years, and the painting I am most proud of is one I never finished. It sits in the corner of my studio, half sky and half suggestion, the colors bleeding into each other in ways I could never reproduce if I tried. I started it on a Tuesday in October when the light was doing something extraordinary to the trees outside my window, and I painted for six hours without stopping, without thinking, without any of the careful planning I usually bring to my work. When I finally stepped back, I saw that the painting had become something I hadn't intended—not the landscape I was looking at but the feeling of looking at it. I picked up my brush to finish it, then put it down. Finishing would mean choosing an ending, and some things are better left in the middle of becoming.`),
  mk('ela.reading.inference', 2, 'What does this passage reveal about the character\'s values?',
    'He values integrity and honesty even when it costs him personally.',
    'He values money above everything.', 'He doesn\'t care about his job.', 'He is dishonest.',
    'Refusing to change results despite pressure shows commitment to integrity.',
    'He sacrifices money for principle', 'His distress shows he cares deeply',
    ['reading-comprehension', 'inference'], ['inference'],
    `The report was due Friday, and the numbers didn't say what the client wanted to hear. Marcus stared at his spreadsheet, checking the calculations for the fifth time. The data was clear: the proposed development would increase flooding risk in the downstream neighborhoods by 40%. His boss had already hinted, in that way bosses hint, that "flexibility" in the interpretation would be "appreciated." The client was the firm's biggest account. Marcus thought about his mortgage, his daughter's tuition, the promotion he'd been working toward for three years. Then he thought about the families in those downstream neighborhoods, who would never know his name or what he had done for them. He saved the file, attached it to an email to his boss with the subject line "Final Report—No Changes," and pressed send. His hand was steady. His stomach was not.`),
  mk('ela.reading.claim_evidence', 1, 'What claim does this passage support?',
    'Reading fiction develops empathy by allowing readers to experience others\' perspectives.',
    'Only nonfiction is educational.', 'Reading is boring.', 'Empathy cannot be learned.',
    'The brain studies showing perspective-taking during fiction reading support empathy development.',
    'The passage argues fiction is valuable', 'The passage provides scientific evidence for empathy growth',
    ['reading-comprehension'], ['claim-evidence'],
    `Neuroscience research has revealed that reading fiction activates the same brain regions involved in real-life social interactions. When readers engage with a character's experiences, their brains simulate those experiences—a phenomenon psychologists call "experience-taking." fMRI studies show that the brain regions associated with understanding others' mental states become more active during fiction reading than during nonfiction reading. A study at The New School found that participants who read literary fiction performed significantly better on tests of empathy and emotional intelligence than those who read nonfiction or popular fiction. The researchers suggest that literary fiction, with its complex characters and ambiguous situations, requires readers to actively infer characters' thoughts and feelings—essentially practicing empathy. This has implications for education: incorporating more fiction into school curricula could help develop the social-emotional skills that standardized tests fail to measure.`),
  mk('ela.reading.inference', 1, 'What can you infer about the neighborhood?',
    'It is a close-knit community where people help each other.',
    'People in the neighborhood don\'t interact.', 'It is a dangerous place.', 'Nobody has lived there long.',
    'The chain of favors shows neighbors actively supporting each other.',
    'Multiple interactions show connection', 'The actions are all positive and supportive',
    ['reading-comprehension', 'inference'], ['inference'],
    `When the Johnsons' pipes froze in January, Mr. Delgado from two doors down showed up with a space heater before anyone asked. When Mr. Delgado's car wouldn't start the next week, Mrs. Kim drove him to work without being called. When Mrs. Kim's daughter needed a last-minute babysitter, the Johnsons took her in for the evening. Nobody kept score. Nobody expected repayment. The favors circulated through the block like a current, powering something larger than any individual act. The new family that moved in on the corner—the Nguyens—received a welcome basket from someone, though nobody could quite remember who organized it. "That's just how it works here," Mrs. Johnson explained when the Nguyens asked who to thank. "You'll help someone next week, and the week after that, someone will help you."`),
  mk('ela.reading.best_evidence', 2, 'Which detail best supports the inference that the character is self-taught?',
    '"Every technique she knew had been learned from YouTube tutorials and library books."',
    '"She worked in a professional studio."', '"Her paintings sold for high prices."', '"She used oil paints."',
    'YouTube tutorials and library books are hallmarks of self-directed, informal learning.',
    'Having a studio doesn\'t indicate formal training', 'Sales don\'t indicate training method',
    ['reading-comprehension'], ['best-evidence'],
    `Lena's paintings hung in a gallery downtown, between works by artists with MFA degrees and decades of formal training. She had neither. Every technique she knew had been learned from YouTube tutorials and library books, practiced in the garage her landlord let her use as a studio in exchange for painting the building's exterior once a year. Her brushstrokes were unconventional—gallery visitors often commented on them—because she had never been told there was a "correct" way to apply paint. The gallery owner had discovered her work at a community art show and offered the exhibition on the spot. "Your work has an authenticity that trained artists spend years trying to achieve," he told her. Lena wasn't sure if that was a compliment or an accident, but she decided it didn't matter.`),
  mk('ela.reading.inference', 2, 'What can you infer about the teacher\'s approach to education?',
    'She believes in making learning relevant to students\' real lives.',
    'She follows the textbook strictly.', 'She doesn\'t care about standards.', 'She only teaches facts.',
    'Using the student\'s neighborhood and connecting lessons to real issues shows relevance-based teaching.',
    'She departs from traditional methods', 'She addresses standards through real-world applications',
    ['reading-comprehension', 'inference'], ['inference'],
    `Ms. Washington never started a math lesson with "open your textbook to page..." Instead, she started with questions. "How many of you walked past the empty lot on Morrison Street this morning?" Every hand went up. "The city wants to build either a parking garage or a community garden there. Today we're going to figure out which one makes more mathematical sense." Over the next week, her eighth-graders calculated square footage, estimated construction costs, projected tax revenue, and analyzed survey data they had collected themselves from neighborhood residents. They presented their findings to a city council member who actually came to the classroom. The parking garage won on revenue, but the garden won on every other metric the students measured. Three months later, the city broke ground on a community garden. Ms. Washington's students watched from the sidewalk, doing the math in their heads.`),
];

// Literary: need 14 more
const lit: Q[] = [
  mk('ela.reading.figurative_language', 1, 'What literary device is "the alarm clock screamed"?',
    'Personification', 'Simile', 'Metaphor', 'Alliteration',
    'Giving a clock the human action of screaming is personification.',
    'The clock made a noise but not literally screaming',
    `Monday announced itself the way it always did—with the alarm clock screaming at 6:15 and the cat knocking something off the nightstand. Tanya buried her face in the pillow, negotiating with the universe for five more minutes. The pillow, warm and understanding, agreed. The universe did not. Her phone buzzed with a reminder about the presentation she wasn't ready for, and the coffee maker—set to brew at 6:00—had apparently gone on strike. She found it blinking an error code that probably translated to "I also don't want to do today." By the time she made it to the kitchen, the cat had knocked over the sugar bowl, creating a small, sparkling desert on the counter that was, Tanya had to admit, kind of beautiful in the morning light.`),
  mk('ela.reading.tone_mood', 2, 'What is the tone of this passage?',
    'Determined and defiant', 'Defeated and hopeless', 'Cheerful and carefree', 'Confused and uncertain',
    'The repetition of "kept going" and overcoming obstacles create a tone of determination.',
    'She overcomes every setback', 'The situation is serious, not lighthearted',
    ['literary-analysis'], ['literary', 'tone-mood'],
    `They said she was too short for basketball, so she practiced her jump shot until it was the best on the team. They said she was too quiet to be student council president, so she wrote speeches that made the auditorium go silent—the good kind of silent. They said she wouldn't get into the honors program because her test scores were "borderline," so she studied until borderline became undeniable. Amira collected doubts the way other people collected trophies, and she used them the same way—as motivation, as fuel, as proof that the people who said "you can't" were really saying "I didn't." She kept going. She always kept going. Not because she didn't hear them, but because she did.`),
  mk('ela.reading.vocabulary_in_context', 1, 'What does "uncharted" mean in this context?',
    'Unknown and unexplored territory', 'A map without markings', 'A canceled subscription', 'A music chart',
    'In context of starting a new life phase, "uncharted" means entering unknown territory.',
    'Figurative meaning, not literal', 'Not related to music',
    ['literary-analysis'], ['literary', 'vocabulary'],
    `The morning after graduation, everything felt uncharted. The schedules that had organized Maya's life for thirteen years—class bells, homework deadlines, practice at 3:30—dissolved overnight, replaced by nothing. She woke at 7:00 out of habit, then lay in bed realizing nobody expected her anywhere. The freedom was dizzying, then terrifying, then dizzying again. Her room, which had been a launchpad for four years of high school, now felt like a museum of a life that was over. The poster above her desk said "The future belongs to those who believe in the beauty of their dreams," which had seemed inspiring yesterday and now seemed like a question she couldn't answer. What did she believe? What were her dreams? She got out of bed and made coffee, because that was at least one thing she knew how to do.`),
  mk('ela.reading.plot_character', 2, 'What does this passage reveal about the narrator\'s growth?',
    'The narrator has learned to see their parent as a complex human being, not just a parent.',
    'The narrator still sees their parent as perfect.', 'The narrator has given up on the relationship.', 'The narrator is becoming more like their parent.',
    'Seeing the father\'s vulnerabilities and history shows evolving, mature perspective.',
    'The passage shows recognition of imperfection', 'The passage shows deepening understanding',
    ['literary-analysis'], ['literary', 'character-development'],
    `I used to think my father was invincible. He fixed everything—leaky faucets, flat tires, broken hearts—with the same quiet competence, as if the world was just a series of problems waiting for his hands. But somewhere in my twenties, I began to see the cracks. The way he went quiet when his brother's name came up. The drawer full of letters he never sent. The fact that he watched the news every night with an intensity that wasn't really about the news. I started to see him not as my father—capital F, role defined—but as David, a man who had lost his mother at twelve, worked since he was fifteen, and carried fears he never named. It didn't make me love him less. It made me love him differently—the way you love a person, not a pedestal.`),
  mk('ela.reading.figurative_language', 3, 'What extended metaphor is used throughout this passage?',
    'Life as a book with chapters, pages, and stories', 'Life as a journey on a road', 'Life as a game', 'Life as a river',
    'Chapters, pages, dog-eared, and spine all extend the book metaphor.',
    'No road imagery is used', 'No game terminology appears',
    ['literary-analysis'], ['literary', 'figurative-language'],
    `My mother's life was a book that she never let anyone read all the way through. She offered chapters selectively—the funny ones about growing up in a small town, the adventurous ones about her year in Paris. But there were pages she kept folded, passages she had dog-eared and skipped over, entire chapters that remained unwritten or, more likely, written in an ink only she could read. I found the book after she died—not literally, of course, but in the boxes of photographs and letters and journals that told the stories she had left out. Some were beautiful. Some were heartbreaking. All of them made me realize that the woman I thought I knew was only the cover of a much longer, more complicated story. I am still reading. I suspect I always will be. The spine of her story is strong enough to hold everything.`),
  mk('ela.reading.tone_mood', 1, 'What mood does this opening create?',
    'Cozy and intimate', 'Terrifying and dark', 'Formal and academic', 'Tense and suspenseful',
    'Warm blanket, cocoa, rain, and fireside imagery create a cozy, intimate atmosphere.',
    'All imagery is warm and safe', 'The language is casual and personal',
    ['literary-analysis'], ['literary', 'tone-mood'],
    `Rain tapped against the window like a polite visitor, and the fire in the woodstove popped and crackled its response. Sophie pulled the blanket tighter around her shoulders—the old quilt, the one that smelled like cedar and laundry soap and her grandmother's house. The cocoa in her mug had cooled to the perfect temperature, and the book in her lap had reached the chapter where everything was about to change. Outside, the world was gray and wet and cold. Inside, the world was the size of this chair, this blanket, this story. The cat materialized from nowhere—as cats do—and settled on her feet with the confidence of a creature who has never once questioned whether it belongs.`),
  mk('ela.reading.figurative_language', 2, 'What does "she wore her confidence like armor" mean?',
    'She used her confident demeanor to protect herself from vulnerability or criticism.',
    'She wore metal clothing.', 'She was very strong physically.', 'She never felt afraid.',
    'The simile compares confidence to armor, suggesting it\'s a protective layer, not natural.',
    'Figurative, not literal', 'Armor implies protection from something—she has vulnerabilities',
    ['literary-analysis'], ['literary', 'figurative-language'],
    `Destiny walked into every room like she owned it—shoulders back, chin up, voice three notches louder than necessary. She wore her confidence like armor, polished and visible, daring anyone to find a chink. Her classmates called her fearless. Her teachers called her bold. Her best friend, Nadia—the only person who had seen Destiny cry in the bathroom after the college rejection—called her brave, which is a different thing entirely. Because fearless means you don't feel afraid. And bold means you don't care what people think. But brave means you feel all of it—the fear, the doubt, the sting of every whispered judgment—and you walk into the room anyway.`),
  mk('ela.reading.vocabulary_in_context', 2, 'What does "gravity" mean in the phrase "the gravity of the situation"?',
    'Seriousness and importance', 'Gravitational force', 'Weight or heaviness', 'Sadness',
    'In context, "gravity" means the serious, weighty nature of what is happening.',
    'Not the physics concept here', 'While related to heaviness, the meaning is figurative seriousness',
    ['literary-analysis'], ['literary', 'vocabulary'],
    `The principal called an all-school assembly, which was unusual enough to generate whispers in every hallway. Students filed into the gymnasium with the casual indifference of people who assume the announcement will be about the dress code or the vending machines. But when they saw the principal's face—drawn tight, eyes red-rimmed—the whispers stopped. The superintendent stood beside her, which never happened for routine announcements. The gravity of the situation settled over the gymnasium like a physical weight. Mrs. Chen spoke slowly, choosing each word with care, and when she said the name of the student who had been in the accident, the gymnasium held its breath. Then, from somewhere in the bleachers, a sound—not quite crying, not quite speaking—broke the silence, and the gravity became unbearable.`),
  mk('ela.reading.plot_character', 1, 'What motivates the character\'s actions in this passage?',
    'A desire to honor her grandmother\'s memory and preserve family traditions.',
    'She wants to make money.', 'She is bored with nothing else to do.', 'Her parents forced her.',
    'Learning the recipe from memory and the emotional connection to her grandmother show motivation by love and legacy.',
    'No commercial motive is present', 'She acts with passion and purpose',
    ['literary-analysis'], ['literary', 'character-development'],
    `Every Sunday morning, Priya woke at 5 a.m. to make her grandmother's biryani. Not from a recipe card—Grandma Lakshmi had never written anything down—but from memory, from the hours Priya had spent standing beside her in the kitchen as a child, watching hands that moved with the certainty of someone who had made this dish a thousand times. The measurements were imprecise: "a handful" of saffron, a "generous" amount of ghee, cardamom pods crushed "until you can smell them from the hallway." It had taken Priya two years after her grandmother's death to get it right—to find the exact ratio of spice to rice that transported her back to that kitchen, that voice, that love expressed through flavor. Now she made it every week and brought portions to the neighbors, not because they had asked but because her grandmother would have.`),
  mk('ela.reading.figurative_language', 3, 'What does the repeated imagery of water represent in this passage?',
    'The overwhelming and uncontrollable nature of grief',
    'The character lives near the ocean.', 'Water represents happiness.', 'The character is thirsty.',
    'Waves, drowning, and flooding as descriptions of grief create a sustained water metaphor.',
    'The water is metaphorical', 'Water represents difficulty, not joy',
    ['literary-analysis'], ['literary', 'figurative-language'],
    `Grief came in waves. Everyone said that, and it was true, but nobody told her what kind of waves. Some days it was a gentle lap at the ankles—a reminder, a whisper, something she could walk through. Other days it was a rogue wave that knocked her flat, pulled her under, held her there until she forgot which way was up. She learned to swim in it, eventually. Not to stay dry—that was impossible—but to float, to breathe, to let the current carry her without fighting it. Some mornings she woke up dry. Other mornings she woke up drowning. But she kept waking up, which was, she supposed, its own kind of survival. Her therapist called it resilience. She called it stubbornness. Either way, it kept her head above water—most days—and most days were enough.`),
  mk('ela.reading.tone_mood', 3, 'How does the author create a sense of urgency in this passage?',
    'Through short sentences, present tense, and a ticking clock.',
    'Through long, descriptive paragraphs.', 'Through calm, measured language.', 'Through flashbacks.',
    'Staccato rhythm, time references, and present tense create immediacy and urgency.',
    'Sentences are deliberately short and punchy', 'The language is the opposite of calm',
    ['literary-analysis'], ['literary', 'tone-mood'],
    `The clock reads 11:47. Thirteen minutes. The lab door is locked from the outside. Ava's fingers fly across the keyboard, each keystroke a prayer. The code she needs to crack has 256-bit encryption. The virus she needs to stop has already reached three networks. Eleven minutes. Her screen flashes red—access denied—and she starts over. Somewhere above her, footsteps. The building's security system has been compromised; she compromised it herself to get in here. Nine minutes. The ventilation system hums. The server banks glow blue and patient, indifferent to the catastrophe flowing through their circuits. Seven minutes. Ava's hands are steady. Her heart is not. She finds the vulnerability on the third try—a missing semicolon in line 4,847 that nobody noticed because nobody was looking. Five minutes. She writes the patch. Three minutes. She uploads. One minute. The screen goes green. The clock reads 11:59.`),
  mk('ela.reading.plot_character', 3, 'What does this passage suggest about the nature of leadership?',
    'Effective leadership involves listening and empowering others rather than commanding.',
    'Leaders must always make decisions alone.', 'Leadership requires being the loudest voice.', 'Good leaders never show weakness.',
    'The captain\'s approach of listening, asking questions, and sharing credit demonstrates empowering leadership.',
    'She actively involves others', 'She leads through questions, not volume',
    ['literary-analysis'], ['literary', 'character-development'],
    `Captain Torres led differently than anyone expected. She didn't give speeches. She didn't raise her voice. She didn't make unilateral decisions and announce them from on high. Instead, she asked questions. "What do you see that I'm missing?" she would ask her crew. "What would you do?" At first, they thought it was a test—that she had the answer and was waiting for them to find it. But slowly they realized she was genuinely listening. When the solution worked, she credited the crew. When it didn't, she took the blame herself. "A captain who needs to be the smartest person in the room has already failed," she told a young officer who asked about her approach. "My job isn't to have all the answers. My job is to create a team where the answers can come from anyone." Her ship had the highest retention rate in the fleet. Nobody wanted to leave.`),
  mk('ela.reading.figurative_language', 1, 'What literary device is "the branches whispered secrets to each other"?',
    'Personification', 'Simile', 'Hyperbole', 'Alliteration',
    'Giving branches the human ability to whisper and share secrets is personification.',
    'No "like" or "as"—not a simile', 'Not an exaggeration—it\'s attribution of human qualities',
    ['literary-analysis'], ['literary', 'figurative-language'],
    `The old oak tree stood in the center of the schoolyard like a patient teacher waiting for class to begin. Its branches whispered secrets to each other when the wind blew, sharing stories that had accumulated over a hundred years of watching children grow. Students carved their initials into its trunk—declarations of love and friendship that the tree absorbed without complaint, wearing their marks like tattoos. In spring, it scattered blossoms across the playground like confetti at a celebration nobody had planned. In winter, its bare branches reached toward the sky like outstretched arms asking for something—warmth, perhaps, or the return of the children who had gone inside. The school board discussed removing it once, citing root damage to nearby pipes. The petition to save it got more signatures than the petition to improve school lunches, which tells you everything about priorities.`),
  mk('ela.reading.tone_mood', 2, 'What is the predominant tone of this passage?',
    'Reflective and philosophical', 'Sarcastic and mocking', 'Panicked and anxious', 'Festive and celebratory',
    'The questions about identity and the thoughtful observations create a reflective, philosophical tone.',
    'The narrator is sincere, not sarcastic', 'The mood is calm and contemplative',
    ['literary-analysis'], ['literary', 'tone-mood'],
    `At some point between childhood and whatever this is, I stopped knowing who I was. Not in a dramatic, existential-crisis way—more in a quiet, Tuesday-afternoon way. I was standing in the grocery store, choosing between two brands of pasta sauce, and I realized I had no idea which one I actually preferred. I'd been buying the one my mother bought, then the one my college roommate recommended, then the one my ex liked. None of them were mine. I put both jars back and stood in the aisle for what felt like a long time, thinking about all the choices I'd made not out of preference but out of proximity—the career I fell into because it was there, the city I lived in because I'd never left, the person I was becoming because I'd never stopped to ask if it was the person I wanted to be. I bought neither sauce. I went home and made something from scratch. It wasn't great, but it was mine.`),
];

function append(filename: string, extras: Q[]) {
  const path = resolve(outDir, filename);
  const existing: Q[] = JSON.parse(readFileSync(path, 'utf-8'));
  const combined = [...existing, ...extras];
  writeFileSync(path, JSON.stringify(combined, null, 2));
  console.log(`${filename}: ${existing.length} + ${extras.length} = ${combined.length}`);
}

append('round2_ela_main_idea.json', mi);
append('round2_ela_inference.json', inf);
append('round2_ela_literary.json', lit);
