import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const outDir = resolve(__dirname, '..', 'content', 'questions');

interface Question {
  section: string; category: string; difficulty: number; type: string;
  stem: string; stimulus?: string; options: { label: string; text: string }[];
  correctAnswer: string; explanation: string;
  commonMistakes: { label: string; explanation: string }[];
  skills: string[]; tags: string[];
}

function randDiff(): number { const r = Math.random(); return r < 0.3 ? 1 : r < 0.7 ? 2 : 3; }

function mkQ(cat: string, diff: number, stem: string, correct: string, w1: string, w2: string, w3: string, exp: string, cm1: string, cm2: string, skills: string[], tags: string[], stimulus: string): Question {
  return {
    section: 'ela', category: cat, difficulty: diff, type: 'multiple_choice',
    stem, stimulus,
    options: [
      { label: 'A', text: correct },
      { label: 'B', text: w1 },
      { label: 'C', text: w2 },
      { label: 'D', text: w3 },
    ],
    correctAnswer: 'A', explanation: exp,
    commonMistakes: [{ label: 'B', explanation: cm1 }, { label: 'C', explanation: cm2 }],
    skills, tags,
  };
}

// ===== MAIN IDEA EXTRAS (27 needed) =====
const mainIdeaExtras: Question[] = [
  mkQ('ela.reading.main_idea', randDiff(), 'What is the main idea of this passage?',
    'Vertical farming offers a sustainable solution to urban food production challenges.',
    'Vertical farms are too expensive to operate.', 'Only lettuce can be grown vertically.', 'Traditional farming is obsolete.',
    'The passage discusses multiple advantages of vertical farming for cities.',
    'Too narrow—cost is mentioned but not the focus', 'Unsupported by the passage',
    ['reading-comprehension'], ['main-idea'],
    `Vertical farming—growing crops in stacked layers inside controlled environments—is gaining traction as a solution to the challenges of feeding growing urban populations. These indoor farms use LED lighting, hydroponics, and climate control to produce crops year-round, regardless of weather or season. A single vertical farm can produce the same yield as 30 acres of traditional farmland while using 95% less water. Because the farms can be built in warehouses within cities, transportation costs and carbon emissions from shipping produce are dramatically reduced. Companies like AeroFarms and Plenty have attracted billions in investment, and cities from Singapore to Newark are integrating vertical farms into their food infrastructure. Critics note the high energy costs of LED lighting, but advances in renewable energy and LED efficiency are steadily closing this gap.`),

  mkQ('ela.reading.authors_purpose', randDiff(), "What is the author's primary purpose?",
    'To explain how music therapy benefits patients with neurological conditions',
    'To argue that music should replace traditional medicine', 'To describe how to become a music therapist', 'To compare different genres of music',
    'The passage informs about research findings on music therapy for neurological patients.',
    'Too extreme—passage doesn\'t advocate replacement', 'Not addressed in the passage',
    ['reading-comprehension'], ['authors-purpose'],
    `Music therapy has emerged as a promising complementary treatment for patients with neurological conditions such as Parkinson's disease, stroke recovery, and traumatic brain injury. Research from Johns Hopkins University shows that rhythmic auditory stimulation—essentially, moving to a steady beat—can help Parkinson's patients improve their gait and reduce freezing episodes. For stroke survivors, singing therapy has helped patients who lost the ability to speak regain language function by engaging different neural pathways. The mechanism appears related to neuroplasticity: music activates multiple brain regions simultaneously, creating alternative neural networks that can compensate for damaged areas. While music therapy is not a replacement for conventional treatment, its low cost, accessibility, and lack of side effects make it an attractive addition to rehabilitation programs.`),

  mkQ('ela.reading.text_structure', randDiff(), 'How is this passage organized?',
    'A historical problem followed by technological solutions and their limitations',
    'Chronological narrative', 'Compare and contrast of two technologies', 'Persuasive argument with counterarguments',
    'The passage presents the problem (food waste), solutions (technology), and acknowledges limitations.',
    'Not purely chronological', 'Only two items aren\'t compared systematically',
    ['reading-comprehension'], ['text-structure'],
    `Food waste is one of the world's most pressing yet solvable environmental problems. Roughly one-third of all food produced globally is lost or wasted, contributing to 8-10% of greenhouse gas emissions. Technology is increasingly being deployed to combat this waste at every stage of the supply chain. AI-powered systems from companies like Afresh help grocery stores predict demand more accurately, reducing over-ordering. Apps like Too Good To Go connect consumers with restaurants and bakeries selling surplus food at discounted prices. At the farm level, imperfect produce that was once discarded is now being sold through services like Misfits Market and Imperfect Foods. Even food that cannot be saved for human consumption is being converted to animal feed or composted using industrial-scale systems. Despite these innovations, experts emphasize that technology alone cannot solve the problem—cultural attitudes about food, particularly in wealthy nations where abundance is taken for granted, must also change.`),

  mkQ('ela.reading.main_idea', randDiff(), 'What is the central idea of this passage?',
    'Bees are essential pollinators whose decline threatens global food security.',
    'Honey production is declining worldwide.', 'Pesticides should be completely banned.', 'Only honeybees pollinate crops.',
    'The passage focuses on bees\' role in pollination and the consequences of their decline.',
    'Honey is mentioned but not the main focus', 'The passage discusses multiple causes, not just pesticides',
    ['reading-comprehension'], ['main-idea'],
    `Bees pollinate approximately 75% of the fruits, nuts, and vegetables grown in the United States, making them indispensable to agriculture. Yet bee populations have been declining at alarming rates. Colony Collapse Disorder, first identified in 2006, has caused beekeepers to lose an average of 30-40% of their hives each winter. Scientists attribute the decline to a combination of factors: pesticides (particularly neonicotinoids), habitat loss, parasites like the Varroa mite, and climate change disrupting flowering patterns. The economic impact is staggering—pollination services provided by bees are valued at over $15 billion annually in the U.S. alone. Communities and governments are responding with pollinator-friendly initiatives, including planting wildflower corridors, restricting certain pesticides, and supporting research into bee health. Without these efforts, experts warn, the consequences for global food security could be severe.`),

  mkQ('ela.reading.main_idea', randDiff(), 'What is the main idea?',
    'Ancient civilizations independently developed writing systems to meet practical needs.',
    'All writing came from Mesopotamia.', 'Writing was invented for poetry.', 'Hieroglyphics are the oldest writing.',
    'The passage shows multiple civilizations creating writing independently for practical purposes.',
    'The passage explicitly states independent development', 'Not stated in the passage',
    ['reading-comprehension'], ['main-idea'],
    `Writing was invented independently at least three times in human history—in Mesopotamia around 3400 BCE, in China around 1200 BCE, and in Mesoamerica around 600 BCE. In each case, the initial motivation was practical rather than literary. Mesopotamian cuneiform began as a system for tracking grain stores and tax payments. Chinese oracle bone script was used for divination—posing questions to ancestors and recording their answers. Mayan glyphs recorded royal lineages, astronomical observations, and calendar calculations. Only over centuries did these practical systems evolve to express the full range of human thought, from epic poetry to legal codes to personal letters. The parallel development of writing across unconnected civilizations suggests something fundamental about human cognitive development: when societies reach a certain level of complexity, the need to record and communicate information becomes irresistible.`),

  mkQ('ela.reading.authors_purpose', randDiff(), "What is the author's purpose?",
    'To explain the psychological science behind why habits are hard to break and how to change them',
    'To promote a specific self-help program', 'To argue that habits are impossible to change', 'To compare good and bad habits',
    'The passage explains the neurological basis of habits and evidence-based strategies for change.',
    'No program is promoted', 'The passage explicitly discusses how to change habits',
    ['reading-comprehension'], ['authors-purpose'],
    `Breaking a habit feels impossibly hard because, neurologically, it is. When we repeat a behavior—checking our phone, reaching for a snack, biting our nails—the brain creates and strengthens neural pathways that automate the action. Over time, the behavior moves from the prefrontal cortex (conscious decision-making) to the basal ganglia (automatic behavior), requiring less and less conscious effort to trigger. This is why willpower alone often fails: you're essentially fighting your own brain's efficiency. Research by psychologist Wendy Wood at the University of Southern California suggests that the most effective strategy is not to resist the old habit but to replace it. By identifying the cue that triggers the habitual behavior and substituting a new response that provides a similar reward, individuals can gradually overwrite the old neural pathway. Studies show that it takes an average of 66 days—not the commonly cited 21—for a new behavior to become automatic.`),

  mkQ('ela.reading.text_structure', randDiff(), 'What text structure is primarily used?',
    'Compare and contrast between two approaches to language learning',
    'Chronological order', 'Problem and solution', 'Cause and effect',
    'The passage systematically compares traditional classroom learning with immersion approaches.',
    'Events aren\'t ordered by time', 'The passage compares methods rather than solving a specific problem',
    ['reading-comprehension'], ['text-structure'],
    `Language acquisition researchers have long debated two fundamentally different approaches to learning a second language. Traditional classroom instruction emphasizes grammar rules, vocabulary memorization, and structured exercises. Students learn to conjugate verbs, identify parts of speech, and translate between languages. This approach produces learners who understand the rules of a language but often struggle to use it spontaneously in conversation. Immersion-based approaches, by contrast, prioritize communication over correctness. Students are surrounded by the target language and encouraged to speak from day one, even if their grammar is imperfect. Research shows that immersion learners develop conversational fluency faster and retain language skills longer, but they may develop persistent grammatical errors that are difficult to correct later. Most modern language programs now blend both approaches, using structured instruction to build a foundation while incorporating immersive activities to develop practical communication skills.`),

  mkQ('ela.reading.main_idea', randDiff(), 'What is the central argument?',
    'Public libraries have evolved into essential community hubs that serve far more than readers.',
    'Libraries are becoming obsolete due to the internet.', 'Libraries should only contain books.', 'Librarians are social workers.',
    'The passage describes libraries\' expanded roles as community centers, tech hubs, and social services.',
    'Directly contradicted by the passage', 'Too narrow—books are one of many services discussed',
    ['reading-comprehension'], ['main-idea'],
    `The modern public library bears little resemblance to the hushed, book-lined institutions of popular imagination. Today's libraries serve as community technology centers, providing free internet access and computer literacy classes to residents who lack home connectivity. They function as warming centers during winter storms and cooling centers during heat waves. Librarians help patrons navigate government benefit applications, job searches, and citizenship paperwork. Many libraries now offer tool lending programs, seed libraries, recording studios, and 3D printing labs. In cities facing opioid crises, some libraries have trained staff in naloxone administration and partnered with social service agencies to connect patrons with treatment. Critics who question the relevance of libraries in the digital age miss the fundamental point: libraries have always been about providing free access to resources and information. The resources have simply expanded beyond books.`),

  mkQ('ela.reading.main_idea', randDiff(), 'What is the main idea?',
    'Light pollution has widespread negative effects on ecosystems, health, and scientific observation.',
    'Cities use too much electricity.', 'Stargazing is a popular hobby.', 'LEDs have solved all lighting problems.',
    'The passage covers ecological, health, and scientific consequences of light pollution.',
    'Electricity use is a cause, not the main idea', 'Not the focus of the passage',
    ['reading-comprehension'], ['main-idea'],
    `For most of human history, the night sky was a source of wonder, navigation, and storytelling. Today, more than 80% of the world's population lives under light-polluted skies, and a third of humanity can no longer see the Milky Way. The consequences extend far beyond lost stargazing. Artificial light at night disrupts the circadian rhythms of countless species: sea turtle hatchlings, guided by moonlight, crawl toward brightly lit roads instead of the ocean. Migratory birds, confused by city lights, crash into illuminated buildings by the millions each year. In humans, exposure to artificial light at night suppresses melatonin production, which has been linked to increased rates of insomnia, obesity, and certain cancers. Astronomers, meanwhile, must build observatories in increasingly remote locations to escape the glow. Solutions exist—shielded fixtures, warm-colored LEDs, and smart lighting that dims when not needed—but implementation requires awareness that most people don't yet have.`),

  mkQ('ela.reading.authors_purpose', randDiff(), "What is the author's purpose in this passage?",
    'To explain the science of taste and challenge common misconceptions about it',
    'To teach readers how to cook', 'To rank the five tastes', 'To argue that some people have better taste',
    'The passage corrects the tongue-map myth and explains modern understanding of taste.',
    'Cooking is not discussed', 'No ranking is provided',
    ['reading-comprehension'], ['authors-purpose'],
    `The tongue map—that familiar diagram showing sweet at the tip, salty on the sides, sour further back, and bitter at the rear—is one of the most enduring myths in science education. First introduced through a misinterpretation of a German research paper in 1901, the map suggests that different areas of the tongue detect different tastes. In reality, all taste buds can detect all five basic tastes: sweet, sour, salty, bitter, and umami (a savory taste identified by Japanese chemist Kikunae Ikeda in 1908). What we experience as "flavor" is actually a complex integration of taste, smell, texture, temperature, and even sound. Research shows that up to 80% of what we perceive as taste actually comes from our sense of smell, which is why food seems bland when you have a cold. Individual sensitivity varies enormously: some people, called "supertasters," have significantly more taste buds than average, making bitter flavors particularly intense.`),

  mkQ('ela.reading.text_structure', randDiff(), 'How is this passage primarily organized?',
    'Cause and effect, showing how one event triggered a chain of consequences',
    'Problem and solution', 'Compare and contrast', 'Description only',
    'The passage traces how the Chernobyl disaster caused a series of environmental and human consequences.',
    'Solutions aren\'t the focus', 'Two things aren\'t being compared',
    ['reading-comprehension'], ['text-structure'],
    `On April 26, 1986, a safety test at the Chernobyl Nuclear Power Plant in Ukraine went catastrophically wrong, causing the worst nuclear disaster in history. The explosion released 400 times more radiation than the Hiroshima bomb, contaminating an area spanning thousands of square miles across Ukraine, Belarus, and Russia. The immediate human toll was devastating: 31 workers and firefighters died within months from acute radiation syndrome. In the years that followed, thyroid cancer rates among children in affected areas increased dramatically, and an estimated 350,000 people were permanently relocated from the exclusion zone. The environmental effects were equally profound: forests turned red and died, livestock developed mutations, and the radioactive contamination entered the food chain through soil and water. Paradoxically, the exclusion zone has since become an unintentional wildlife sanctuary, with populations of wolves, wild horses, and even European bison thriving in the absence of human activity.`),

  mkQ('ela.reading.main_idea', randDiff(), 'What is the main idea?',
    'The invention of the telescope fundamentally transformed humanity\'s understanding of the universe.',
    'Galileo invented the telescope.', 'Telescopes are used to look at stars.', 'Modern telescopes are very large.',
    'The passage traces how telescopes changed our cosmic perspective from geocentric to heliocentric and beyond.',
    'Galileo improved but didn\'t invent the telescope, and the passage is broader', 'Too simplistic',
    ['reading-comprehension'], ['main-idea'],
    `When Galileo Galilei first pointed a telescope at the night sky in 1609, he set in motion a revolution in human thought. His observations—mountains on the Moon, moons orbiting Jupiter, phases of Venus—provided evidence that Earth was not the center of the universe, as the Church taught, but merely one planet orbiting the Sun. In the centuries that followed, telescopes grew in size and sophistication, revealing an ever-larger cosmos. William Herschel discovered Uranus in 1781, doubling the known size of the solar system. Edwin Hubble showed in the 1920s that our Milky Way was just one of billions of galaxies. Today, the James Webb Space Telescope peers back to the earliest galaxies formed after the Big Bang, 13.5 billion years ago. Each advance in telescope technology has forced humanity to reconsider its place in the universe—from the center of creation to an insignificant speck in an incomprehensibly vast cosmos.`),

  mkQ('ela.reading.main_idea', randDiff(), 'What is the main idea?',
    'Microplastics are pervasive contaminants found throughout the environment and in human bodies.',
    'Plastic bottles should be recycled.', 'Microplastics only affect ocean life.', 'All plastic is dangerous.',
    'The passage describes the widespread presence of microplastics in diverse environments and organisms.',
    'Recycling is not the focus', 'The passage shows they\'re found everywhere, not just oceans',
    ['reading-comprehension'], ['main-idea'],
    `Microplastics—fragments smaller than 5 millimeters—have been found in virtually every environment on Earth. They contaminate the deepest ocean trenches, the summit of Mount Everest, Arctic sea ice, and remote alpine lakes. They have been detected in the placentas of unborn babies, in human blood, and in the lungs of living patients. These tiny particles originate from the breakdown of larger plastic items, from synthetic clothing fibers released during washing, and from microbeads in personal care products. A single load of laundry can release up to 700,000 microfibers into waterways. Research on the health effects is still in early stages, but laboratory studies suggest that microplastics can cause inflammation, cellular damage, and may act as carriers for toxic chemicals. The scale of contamination has led some scientists to propose that microplastics should be considered a defining feature of the Anthropocene—the current geological age shaped by human activity.`),

  mkQ('ela.reading.authors_purpose', randDiff(), "What is the author's purpose?",
    'To inform readers about the decline of insects and why it matters',
    'To argue that all pesticides should be banned immediately', 'To describe insect anatomy', 'To compare insects to mammals',
    'The passage presents evidence of decline and explains ecological importance of insects.',
    'The passage discusses causes but doesn\'t advocate a single solution', 'Not about anatomy',
    ['reading-comprehension'], ['authors-purpose'],
    `Scientists call it the "insect apocalypse." Studies from Germany, Puerto Rico, and across North America have documented dramatic declines in insect populations—in some regions, by more than 75% over three decades. The causes are familiar: habitat destruction, pesticide use, light pollution, and climate change. What makes insect decline particularly alarming is the cascade of consequences it triggers. Insects pollinate 88% of flowering plants. They decompose organic matter, returning nutrients to soil. They form the base of food webs that support birds, bats, fish, and amphibians—all of which are also declining. A world without insects would see crop failures, ecosystem collapse, and mass extinction of species that depend on them. E.O. Wilson called insects "the little things that run the world," and the evidence increasingly suggests he was right.`),

  mkQ('ela.reading.text_structure', randDiff(), 'What text structure does the author use?',
    'Problem description followed by multiple proposed solutions',
    'Chronological narrative', 'Compare and contrast', 'Cause and effect only',
    'The passage identifies the digital divide problem then presents several solution approaches.',
    'Not a time-ordered narrative', 'The focus is on presenting solutions',
    ['reading-comprehension'], ['text-structure'],
    `The digital divide—the gap between those who have access to modern information technology and those who don't—remains one of the most significant barriers to economic equality in the 21st century. In the United States alone, approximately 21 million people lack access to broadband internet. In rural communities, the figure is even higher, with some areas having no internet infrastructure at all. The consequences are severe: students without home internet fall behind academically, job seekers cannot access online applications, and telehealth services remain out of reach. Several approaches are being pursued to close this gap. The federal government has allocated $65 billion for broadband infrastructure through the Infrastructure Investment and Jobs Act. Private companies like SpaceX's Starlink are deploying satellite internet to reach remote areas. Community mesh networks, built and maintained by local residents, offer a grassroots alternative. Libraries and schools continue to serve as public access points, though demand often exceeds capacity.`),

  mkQ('ela.reading.main_idea', randDiff(), 'What is the main idea?',
    'Sleep plays a critical role in memory consolidation and learning.',
    'Everyone needs exactly 8 hours of sleep.', 'Dreams predict the future.', 'Sleep is a waste of time.',
    'The passage explains how sleep helps the brain process and store new information.',
    'The passage mentions variation in sleep needs', 'Directly contradicted by the passage',
    ['reading-comprehension'], ['main-idea'],
    `Sleep is not merely a period of inactivity but a critical phase during which the brain consolidates memories, processes emotions, and clears metabolic waste. During slow-wave sleep, the hippocampus replays the day's experiences, transferring important information to long-term storage in the cortex. REM sleep, during which most dreaming occurs, appears to play a role in emotional processing and creative problem-solving. Studies have shown that students who sleep after studying retain significantly more information than those who stay awake. One experiment found that subjects who napped after learning a task performed 40% better than those who didn't. The glymphatic system, discovered in 2012, clears toxic proteins—including those associated with Alzheimer's disease—from the brain during deep sleep. These findings suggest that chronic sleep deprivation doesn't just make people tired; it may actively impair cognitive function and increase the risk of neurodegenerative disease.`),

  mkQ('ela.reading.main_idea', randDiff(), 'What is the main idea?',
    'Forensic science has been revolutionized by DNA technology but still faces significant challenges.',
    'DNA evidence is always correct.', 'Fingerprints are no longer used.', 'All criminals can be caught with DNA.',
    'The passage discusses both the power and limitations of DNA in forensic science.',
    'The passage explicitly discusses error rates', 'Fingerprints are one of many tools still used',
    ['reading-comprehension'], ['main-idea'],
    `DNA analysis has transformed criminal justice since its first use in a court case in 1987. The technology can identify individuals with extraordinary precision—the probability of two unrelated people sharing a DNA profile is approximately one in a billion. Since 1989, DNA evidence has exonerated more than 375 wrongfully convicted individuals in the United States, some of whom had spent decades in prison. However, the technology is not infallible. Contamination, degraded samples, and the interpretation of mixed DNA profiles from multiple contributors can lead to errors. The expansion of DNA databases raises privacy concerns, particularly as genetic genealogy techniques—used famously to identify the Golden State Killer in 2018—can identify individuals through their relatives' DNA submissions to commercial testing services. As the technology advances, society must grapple with balancing the power of DNA identification against the rights of individuals who never consented to be part of a forensic database.`),

  mkQ('ela.reading.authors_purpose', randDiff(), "What is the author's purpose in this passage?",
    'To explain how ocean currents regulate global climate and why their disruption is concerning',
    'To describe how to sail across the Atlantic', 'To argue that climate change is not real', 'To compare the Atlantic and Pacific oceans',
    'The passage informs about ocean circulation patterns and the potential consequences of disruption.',
    'Sailing is not discussed', 'The passage discusses climate change consequences',
    ['reading-comprehension'], ['authors-purpose'],
    `The Atlantic Meridional Overturning Circulation (AMOC) is often called the "global conveyor belt"—a vast system of ocean currents that carries warm water from the tropics northward and cold water southward along the ocean floor. This circulation pattern plays a crucial role in regulating climate, particularly in Europe, which enjoys milder winters than its latitude would suggest thanks to the warmth carried by the Gulf Stream. Recent research has raised alarms that the AMOC is weakening at an unprecedented rate, likely due to the influx of freshwater from melting Greenland ice sheets. Freshwater is less dense than saltwater and disrupts the sinking process that drives the circulation. Climate models suggest that a significant weakening or shutdown of the AMOC could lead to severe cooling in Northern Europe, disrupted monsoon patterns in Africa and Asia, accelerated sea level rise along the U.S. East Coast, and shifts in global precipitation patterns that could affect billions of people.`),

  mkQ('ela.reading.text_structure', randDiff(), 'How is this passage organized?',
    'Sequential description of a process with cause and effect elements',
    'Compare and contrast', 'Problem and solution', 'Persuasive argument',
    'The passage describes the stages of how plastics break down, with effects at each stage.',
    'Two things aren\'t being compared', 'No solution is proposed',
    ['reading-comprehension'], ['text-structure'],
    `When a plastic bottle is tossed into the ocean, its journey of destruction has only begun. Sunlight breaks down the plastic through photodegradation, causing it to become brittle and fragment into smaller and smaller pieces. Wave action accelerates this process, grinding the fragments against sand and rock. Within months, the bottle has become hundreds of microplastic particles. These particles absorb toxic chemicals from the surrounding water, including pesticides and industrial pollutants, concentrating them at levels up to a million times higher than the surrounding seawater. Marine organisms mistake these particles for food. Zooplankton ingest them, small fish eat the zooplankton, larger fish eat the small fish, and the toxins bioaccumulate—increasing in concentration at each level of the food chain. By the time the contamination reaches top predators like tuna, sharks, or dolphins, the toxic load can be significant. Some of these same fish end up on dinner plates, completing the cycle.`),

  mkQ('ela.reading.main_idea', randDiff(), 'What is the main idea?',
    'Indigenous languages worldwide are disappearing rapidly, taking irreplaceable knowledge with them.',
    'Everyone should speak English.', 'Only written languages matter.', 'Language extinction is natural and harmless.',
    'The passage describes language loss and the unique knowledge embedded in indigenous languages.',
    'Contradicted by the passage', 'The passage values oral and unwritten languages',
    ['reading-comprehension'], ['main-idea'],
    `Of the approximately 7,000 languages spoken worldwide, linguists estimate that one dies every two weeks. By the end of this century, half of all existing languages may be extinct. The loss is particularly acute among indigenous languages: in Australia, only 13 of the original 250 Aboriginal languages are still learned by children. In North America, of the more than 300 languages spoken before European contact, fewer than 20 are being transmitted to new generations. When a language dies, far more than words are lost. Indigenous languages often encode ecological knowledge accumulated over millennia—the Inuit have dozens of terms for different types of ice, each reflecting subtle observations critical for survival. The Pirahã language of the Amazon lacks number words, challenging fundamental assumptions about human cognition. Revitalization efforts, from Hawaiian language immersion schools to digital archives of endangered languages, offer hope, but the pace of loss far outstrips the pace of preservation.`),

  mkQ('ela.reading.main_idea', randDiff(), 'What is the main idea?',
    'The gut-brain connection shows that digestive health significantly influences mental health.',
    'You should eat more yogurt.', 'The brain controls all body functions directly.', 'Depression has no physical causes.',
    'The passage explains the bidirectional relationship between gut microbiome and mental health.',
    'Too specific and prescriptive', 'The passage shows the gut also influences the brain',
    ['reading-comprehension'], ['main-idea'],
    `The gut has been called the "second brain," and research increasingly shows this is more than a metaphor. The enteric nervous system—a network of 500 million neurons lining the digestive tract—communicates constantly with the brain through the vagus nerve, hormones, and immune system signals. Studies have found that people with depression and anxiety often have distinctly different gut microbiome compositions than healthy controls. In animal studies, transferring gut bacteria from depressed mice to healthy mice caused the healthy mice to develop depressive behaviors. Clinical trials in humans have shown that certain probiotics can reduce symptoms of anxiety and depression, leading researchers to coin the term "psychobiotics." The implications are profound: mental health may be influenced not just by brain chemistry but by the trillions of microorganisms living in our digestive systems. This emerging field is already changing how some clinicians approach treatment, with dietary recommendations becoming part of mental health care plans.`),

  mkQ('ela.reading.authors_purpose', randDiff(), "What is the author's purpose?",
    'To explain how trees communicate and cooperate through underground fungal networks',
    'To argue that trees have human-like emotions', 'To teach readers how to grow mushrooms', 'To describe photosynthesis',
    'The passage informs about the "Wood Wide Web" and its role in forest ecology.',
    'The passage uses scientific evidence, not emotional attribution', 'Mushroom growing is not discussed',
    ['reading-comprehension'], ['authors-purpose'],
    `Beneath the forest floor lies an invisible internet. Mycorrhizal fungi form vast networks connecting the roots of trees, enabling them to share nutrients, water, and chemical signals. Ecologist Suzanne Simard's pioneering research revealed that trees use these fungal networks—dubbed the "Wood Wide Web"—to transfer carbon and other resources to neighboring trees, including seedlings struggling in the shade. Mother trees, the largest and oldest in a forest, serve as hubs in this network, supporting hundreds of younger trees. When a tree is injured or dying, it can dump its resources into the network for its neighbors to absorb. Trees under attack by insects release chemical signals through the network, warning nearby trees to produce defensive compounds before the insects arrive. These findings challenge the traditional view of forests as collections of individual trees competing for resources, revealing instead a cooperative community connected by fungal partnerships.`),

  mkQ('ela.reading.text_structure', randDiff(), 'How is this passage organized?',
    'Chronological development of a scientific understanding',
    'Compare and contrast', 'Problem and solution', 'Spatial order',
    'The passage traces the history of plate tectonics from Wegener through modern understanding.',
    'Only one theory is discussed', 'No specific problem is solved',
    ['reading-comprehension'], ['text-structure'],
    `In 1912, German meteorologist Alfred Wegener proposed that the continents had once been joined in a single landmass he called Pangaea. His evidence was compelling—matching fossils on separate continents, jigsaw-like coastlines, and identical rock formations on opposite sides of the Atlantic—but the scientific establishment dismissed him because he couldn't explain how continents moved. It wasn't until the 1960s that the mechanism was discovered: the seafloor was spreading. Harry Hess proposed that new oceanic crust forms at mid-ocean ridges and pushes older crust outward, carrying continents with it. The theory of plate tectonics unified geology, explaining earthquakes, volcanoes, mountain building, and ocean formation through the movements of rigid plates on Earth's surface. Today, GPS measurements confirm that the plates move at roughly the speed fingernails grow—a few centimeters per year—slowly but relentlessly reshaping the face of our planet.`),

  mkQ('ela.reading.main_idea', randDiff(), 'What is the main idea?',
    'The green revolution saved billions from famine but created environmental problems that need addressing.',
    'Norman Borlaug solved world hunger permanently.', 'Chemical fertilizers are always good.', 'India does not need modern farming.',
    'The passage presents both the achievements and drawbacks of the green revolution.',
    'The passage discusses ongoing challenges', 'The passage shows both benefits and costs',
    ['reading-comprehension'], ['main-idea'],
    `The Green Revolution of the 1960s and 1970s—led by agricultural scientist Norman Borlaug—introduced high-yield crop varieties, chemical fertilizers, and irrigation techniques that dramatically increased food production in developing nations. India, which had faced recurring famines, became self-sufficient in grain production within two decades. Global wheat yields nearly doubled between 1960 and 2000, and Borlaug's work is credited with saving over a billion people from starvation. However, the Green Revolution's legacy is complicated. The intensive farming methods it promoted have led to soil degradation, water depletion, and chemical runoff that pollutes rivers and creates ocean dead zones. The reliance on a few high-yield varieties has reduced crop genetic diversity, making agriculture more vulnerable to disease and climate change. Today's challenge is to maintain the productivity gains of the Green Revolution while transitioning to more sustainable practices—a goal that scientists call the "Evergreen Revolution."`),

  mkQ('ela.reading.authors_purpose', randDiff(), "What is the author's primary purpose?",
    'To explain how confirmation bias affects decision-making and why it is difficult to overcome',
    'To criticize people who disagree with science', 'To describe how the brain stores memories', 'To argue that humans cannot think rationally',
    'The passage explains the mechanism of confirmation bias and its pervasiveness.',
    'The passage is explanatory, not critical', 'Memory storage is not the focus',
    ['reading-comprehension'], ['authors-purpose'],
    `Confirmation bias—the tendency to seek, interpret, and remember information that confirms our existing beliefs—is perhaps the most pervasive cognitive bias in human thinking. Psychologist Peter Wason first demonstrated the phenomenon in the 1960s, showing that people consistently test hypotheses by looking for confirming evidence rather than trying to disprove them. Social media algorithms amplify this tendency by showing users content that aligns with their preferences, creating "filter bubbles" where alternative viewpoints are rarely encountered. The bias operates unconsciously: even when people believe they are being objective, brain imaging studies show that information consistent with existing beliefs activates reward centers, while contradictory information triggers threat responses. This helps explain why political polarization persists despite widespread access to information—people on both sides of an issue can look at the same data and reach opposite conclusions, each genuinely believing the evidence supports their view.`),
];

// ===== INFERENCE EXTRAS (34 needed) =====
const inferenceExtras: Question[] = [
  mkQ('ela.reading.inference', randDiff(), 'What can you infer about the community described?',
    'The neighborhood is experiencing gentrification and longtime residents feel displaced.',
    'The neighborhood is improving for everyone.', 'The coffee shop is the main problem.', 'Nobody likes change.',
    'Rising rents, departing neighbors, and the narrator\'s unease suggest gentrification anxiety.',
    'The passage shows mixed effects, not universal improvement', 'The coffee shop symbolizes larger changes',
    ['reading-comprehension', 'inference'], ['inference'],
    `The new coffee shop on Elm Street served oat milk lattes and charged seven dollars for avocado toast. Rosa watched it from her porch, the same porch where she'd watched the neighborhood for thirty-two years. The Dominican restaurant next door had become a "fusion tapas bar." The corner bodega was now a "curated market." Each change brought new faces—younger, different—and took familiar ones away. Mr. Kim, who'd run the dry cleaners for twenty years, told Rosa his rent had tripled. He was moving to his daughter's place in New Jersey. Rosa's own landlord had started "improvements"—new floors, fresh paint—that she suspected were preludes to a rent increase she couldn't afford. She sipped her home-brewed coffee and watched a moving truck pull up to the building across the street.`),

  mkQ('ela.reading.best_evidence', randDiff(), 'Which sentence best supports the idea that the experiment had unexpected results?',
    '"The plants in the dark room grew taller than those receiving full sunlight."',
    '"Dr. Park carefully measured each plant."', '"The greenhouse maintained a constant temperature."', '"The experiment lasted eight weeks."',
    'Plants growing taller in darkness directly contradicts expectations, showing an unexpected result.',
    'Describes methodology, not results', 'Describes conditions, not outcomes',
    ['reading-comprehension', 'evidence'], ['best-evidence'],
    `Dr. Park's botany experiment was designed to confirm what every textbook taught: plants need sunlight to thrive. She placed identical seedlings in four conditions—full light, partial light, dim light, and complete darkness—measuring height, leaf count, and chlorophyll content weekly. The results from the first four weeks followed predictions perfectly. But in week five, something unexpected happened. The plants in the dark room grew taller than those receiving full sunlight. Dr. Park rechecked her measurements, then rechecked them again. The dark-grown plants were stretching desperately upward, producing long, pale stems in a phenomenon called etiolation—the plant equivalent of searching for light that isn't there. They were taller, yes, but weaker, thinner, and ultimately less healthy than their sun-fed counterparts. The experiment confirmed the textbooks after all, but not in the way Dr. Park had expected.`),

  mkQ('ela.reading.claim_evidence', randDiff(), 'What claim does this passage best support?',
    'Standardized testing fails to measure many important aspects of student ability.',
    'All tests should be eliminated.', 'Students who score low are unintelligent.', 'Teachers are to blame for low scores.',
    'The passage provides examples of abilities that tests cannot capture.',
    'The passage critiques specific limitations, not all assessment', 'The passage doesn\'t blame anyone',
    ['reading-comprehension', 'claim-evidence'], ['claim-evidence'],
    `When eighth-grader Destiny Williams took the state standardized test, her score placed her in the "below proficient" category. Her teacher, Mrs. Alvarez, was puzzled. Destiny was the student who had organized a schoolwide fundraiser that raised $3,000 for the local food bank, designing the marketing materials, managing volunteers, and speaking at a city council meeting to gain support. She had taught herself to code and built a website for her grandmother's church. She read voraciously—mostly nonfiction about social justice—and could discuss complex issues with nuance that impressed even adults. But the test measured none of this. It measured her ability to answer multiple-choice questions about reading passages she found boring and math problems stripped of any real-world context. "The test tells me what Destiny can do in a testing environment," Mrs. Alvarez told Destiny's mother. "It tells me nothing about what Destiny can do in the world."`),

  mkQ('ela.reading.inference', randDiff(), 'What can you infer about the narrator\'s feelings?',
    'The narrator feels nostalgic and slightly sad about the passage of time.',
    'The narrator is happy about changes.', 'The narrator dislikes their childhood.', 'The narrator wants to be young again.',
    'References to "used to" and the bittersweet tone indicate nostalgia tinged with sadness.',
    'The passage doesn\'t express happiness about change', 'Childhood is remembered fondly',
    ['reading-comprehension', 'inference'], ['inference'],
    `The playground where I scraped my knees is a parking lot now. Smooth asphalt where there used to be wood chips and monkey bars. I drove past it yesterday and almost didn't recognize the corner—the oak tree that shaded the swings is gone too, replaced by a streetlight that hums at night. My daughter, buckled in the backseat, asked why I had slowed down. "No reason," I said. But I was thinking about the summer of 1998, when I was her age and the world was the size of that playground. How the slide was Mount Everest and the sandbox was the Sahara. How time moved in hours that felt like days. Now it moves in years that feel like hours, and I can't find the brakes.`),

  mkQ('ela.reading.inference', randDiff(), 'What can you infer about the relationship between the characters?',
    'They are siblings who handle stress differently but care for each other.',
    'They are strangers meeting for the first time.', 'They dislike each other.', 'One is the other\'s teacher.',
    'Shared parents, opposite reactions, and the protective gesture suggest caring siblings.',
    'Their shared history contradicts this', 'The text shows concern and protectiveness',
    ['reading-comprehension', 'inference'], ['inference'],
    `Mia organized her study materials in color-coded folders while her brother, Jake, spread his across the kitchen table in what looked like organized chaos. Their parents' divorce hearing was tomorrow, and neither of them had mentioned it. Mia had made a study schedule that accounted for every fifteen-minute block until midnight. Jake had eaten an entire bag of chips and was now working on his third energy drink. "You should sleep," Mia said without looking up. "You should relax," Jake replied. Neither followed the other's advice. At 11 p.m., Jake found a blanket and draped it over Mia's shoulders without a word. She pretended not to notice, but she pulled it tighter.`),

  mkQ('ela.reading.best_evidence', randDiff(), 'Which detail best supports the idea that the character has been through this situation before?',
    '"She knew exactly which floorboards to avoid and which window locks were broken."',
    '"The house was dark."', '"She moved quickly through the hallway."', '"The dog was sleeping."',
    'Knowing specific floorboards and lock details requires prior experience navigating the house.',
    'A dark house doesn\'t imply familiarity', 'Speed alone doesn\'t prove experience',
    ['reading-comprehension', 'evidence'], ['best-evidence'],
    `Maya crept through the back door at 1 a.m., sliding her shoes off at the threshold. She knew exactly which floorboards to avoid and which window locks were broken—the third step from the bottom creaked, the hallway runner bunched near the bathroom. The dog, ancient and half-deaf, slept through her entrance as he always did. She made it to her bedroom without turning on a single light, navigated by memory and moonlight. Only when the door was safely closed behind her did she exhale. Her phone buzzed: a text from Sana. "Made it?" Maya typed back: "Pro level. They'll never know I was gone." She set her alarm for 6 a.m. and fell asleep in her clothes.`),

  mkQ('ela.reading.inference', randDiff(), 'What can you infer about the speaker\'s perspective on technology?',
    'The speaker values technology but worries about losing human connection.',
    'The speaker hates all technology.', 'The speaker thinks phones are the most important invention.', 'The speaker is a technology expert.',
    'The anecdote about the family dinner shows concern about phones replacing connection.',
    'The speaker uses technology themselves', 'The passage questions technology\'s effects, not celebrates them',
    ['reading-comprehension', 'inference'], ['inference'],
    `I'm not against phones. I carry one everywhere, same as everyone else. I use it to navigate, to work, to stay connected with people I love who live far away. But last Thanksgiving, I looked up from carving the turkey and saw six faces illuminated by screens. My mother, who had spent two days cooking, was showing my aunt a recipe on Pinterest. My teenage nephew was texting someone who wasn't there instead of talking to the cousins who were. My own husband was "just quickly checking work email." And I thought: we traveled hundreds of miles to sit in the same room and stare at different screens. The cranberry sauce went cold while everyone was somewhere else. I'm not against phones. I just wonder sometimes what they're against.`),

  mkQ('ela.reading.claim_evidence', randDiff(), 'What claim is best supported by this passage?',
    'Wilderness experiences can have profound positive effects on youth development.',
    'All children should live outdoors.', 'Cities are bad for young people.', 'Technology is destroying childhood.',
    'The transformation described in Marcus shows positive developmental effects of wilderness.',
    'The passage discusses a specific program, not permanent living', 'Cities aren\'t criticized',
    ['reading-comprehension', 'claim-evidence'], ['claim-evidence'],
    `Marcus had been expelled from two schools before he turned fourteen. His caseworker, running out of options, enrolled him in a wilderness therapy program in the mountains of North Carolina. For the first three days, Marcus refused to participate. He sat on a rock while the other teens learned to build shelters and purify water. On the fourth day, it rained—hard—and his rock offered no protection. A girl named Keisha, who had her own reasons for being there, wordlessly helped him into the group shelter. Something shifted. Over the following weeks, Marcus learned to build fires, read topographic maps, and cook meals for eight people over a camp stove. His counselor noted that in the wilderness, the social hierarchies that had tormented Marcus at school were irrelevant. What mattered was whether you could tie a knot, carry your weight, and show up for your team. Six months after completing the program, Marcus was back in school, maintaining a B average, and volunteering as a peer mentor.`),

  mkQ('ela.reading.inference', randDiff(), 'What does this passage suggest about the narrator?',
    'The narrator is a first-generation college student navigating an unfamiliar world.',
    'The narrator grew up wealthy.', 'The narrator doesn\'t want to be in college.', 'The narrator\'s parents went to the same college.',
    'Not knowing terms like "office hours" and comparing to parents\' experience suggest first-generation status.',
    'Feeling lost suggests the opposite of privilege', 'The narrator is trying hard, not avoiding college',
    ['reading-comprehension', 'inference'], ['inference'],
    `My roommate mentioned "office hours" on the first day, and I nodded like I knew what that meant. I didn't. I also didn't know what a "syllabus" was, or why everyone seemed to know that you don't actually buy all the textbooks on the list. There were rules here that nobody taught but everyone seemed to know—like an invisible handbook that had been distributed to everyone except me. My parents called every night. "Are you eating?" my mother asked. "Are you studying?" my father added. They were so proud. They had never been inside a college building before move-in day, when they carried my boxes up four flights of stairs and looked around my dorm room like it was a palace. I couldn't tell them that I cried in the shower that first week, or that I ate lunch alone for the first month because I didn't know how to join a table of strangers who all seemed to already know each other.`),

  mkQ('ela.reading.best_evidence', randDiff(), 'Which evidence best supports the claim that the community values tradition?',
    '"The recipe had been passed down through five generations, each adding their own secret ingredient."',
    '"The festival drew thousands of visitors."', '"Local businesses set up booths."', '"The weather was perfect that day."',
    'Five generations of recipe transmission directly demonstrates valuing and preserving tradition.',
    'Visitor numbers show popularity, not tradition', 'Commerce doesn\'t necessarily indicate tradition',
    ['reading-comprehension', 'evidence'], ['best-evidence'],
    `The annual Harvest Festival had been held in Millbrook since 1892, making it one of the oldest continuous community celebrations in the state. The centerpiece was always Mrs. Okonkwo's jollof rice, a recipe that had been passed down through five generations, each adding their own secret ingredient. Her grandmother had brought it from Nigeria; her mother had adapted it with local peppers; Mrs. Okonkwo herself had added a touch of smoked paprika that she would reveal to no one. The festival drew thousands of visitors and local businesses set up booths selling crafts and cider. But what mattered most to residents was the continuity—the knowledge that their great-grandparents had stood in this same field, eaten from the same recipes, and danced to music that, while the instruments changed, carried the same rhythms.`),

  mkQ('ela.reading.inference', randDiff(), 'What can you infer about the principal\'s leadership style?',
    'She leads by example and values actions over words.',
    'She is strict and authoritarian.', 'She doesn\'t care about the school.', 'She is new to the job.',
    'Cleaning up herself and the students following her lead show action-oriented leadership.',
    'Her approach is collaborative, not authoritarian', 'Her knowledge of the school contradicts this',
    ['reading-comprehension', 'inference'], ['inference'],
    `When the water main broke and flooded the school cafeteria at 6 a.m., Principal Gutierrez was the first person there—not the custodians, not the maintenance crew, but the principal herself, in rubber boots and old jeans, pushing a mop. By the time teachers started arriving at 7, she had organized a bucket brigade and was directing traffic with the calm efficiency of someone who had weathered worse. She didn't make announcements or send emails about what "we" needed to do. She just started doing it. Within an hour, students who had arrived early joined in without being asked. The cafeteria was functional by lunch. "I didn't want to miss pizza day," one seventh-grader explained. Principal Gutierrez laughed. She had ordered extra pizza for the volunteers.`),

  mkQ('ela.reading.claim_evidence', randDiff(), 'Which claim does this passage best support?',
    'Early exposure to multiple languages enhances cognitive development.',
    'Bilingual children are always smarter.', 'English is the most important language.', 'Children can only learn one language well.',
    'The research showing better executive function in bilingual children supports cognitive benefits.',
    'The passage discusses tendencies, not absolutes', 'The passage values multilingualism',
    ['reading-comprehension', 'claim-evidence'], ['claim-evidence'],
    `For decades, parents were warned that raising children with two languages would "confuse" them, leading to delayed speech and academic difficulties. This advice, it turns out, was wrong. Research from the University of Washington's Institute for Learning and Brain Sciences shows that bilingual babies as young as 11 months demonstrate enhanced executive function—the ability to focus attention, switch between tasks, and filter irrelevant information. These cognitive advantages persist into adulthood: bilingual individuals consistently outperform monolinguals on tasks requiring mental flexibility and problem-solving. Studies also suggest that bilingualism delays the onset of dementia by an average of 4-5 years. While bilingual children may initially have smaller vocabularies in each individual language, their total vocabulary across both languages typically exceeds that of monolingual peers. The latest research suggests that the mental exercise of managing two language systems strengthens cognitive circuits in much the same way physical exercise strengthens muscles.`),

  mkQ('ela.reading.inference', randDiff(), 'What can you infer about the author\'s view of success?',
    'The author believes success is defined by impact and fulfillment rather than wealth or fame.',
    'The author thinks money equals success.', 'The author believes fame is most important.', 'The author thinks success is impossible.',
    'The contrasting examples show the author values meaningful work over conventional markers.',
    'Directly contradicted by the passage', 'The passage shows multiple paths to success',
    ['reading-comprehension', 'inference'], ['inference'],
    `My college roommate drives a Tesla and lives in a house with more bathrooms than people. By every conventional measure, he is successful. My other college friend teaches third grade in a Title I school, drives a twelve-year-old Honda, and shares a two-bedroom apartment with her cat. She spends her summers writing curriculum and her weekends at yard sales buying books for her classroom library. Last month, a former student—now in high school—wrote her a letter saying that her class was the first time he felt smart. She taped it to her refrigerator next to the others. When I visit my roommate, we talk about his renovation plans. When I visit my teacher friend, we talk about her students, and the conversation lasts until midnight. I have been thinking a lot lately about what we mean when we say someone has "made it."`),

  mkQ('ela.reading.inference', randDiff(), 'What can you infer about the scientist\'s discovery?',
    'The mold she initially tried to discard led to an important accidental discovery.',
    'She planned the experiment carefully.', 'The mold ruined her research completely.', 'She was studying mold intentionally.',
    'Discarding a "contaminated" sample but noticing something remarkable suggests serendipity.',
    'She tried to throw it away initially', 'She noticed something useful in what she thought was ruined',
    ['reading-comprehension', 'inference'], ['inference'],
    `Dr. Torres almost threw away the petri dish. The culture she had been growing for three weeks was contaminated—a fuzzy blue-green mold had colonized one corner, and the bacterial colonies she was studying had retreated from it like a crowd backing away from a fire. She was reaching for the biohazard bin when something made her pause. The bacteria hadn't just moved away from the mold. They had died. In a perfect circle around the mold, there was a clear zone—no bacteria at all. Dr. Torres set the dish under the microscope and leaned in. The mold was producing something. Something that killed bacteria on contact. She pulled out her notebook and began writing, her hand trembling slightly. She had been studying antibiotic resistance for six years. And now, purely by accident, she might have found a new weapon.`),

  mkQ('ela.reading.best_evidence', randDiff(), 'Which detail best supports the inference that the town is struggling economically?',
    '"Half the storefronts on Main Street displayed \'For Lease\' signs."',
    '"The sky was gray."', '"Children played in the park."', '"A dog barked somewhere."',
    'Empty storefronts directly indicate economic decline and business closures.',
    'Weather doesn\'t indicate economy', 'Children playing doesn\'t suggest economic conditions',
    ['reading-comprehension', 'evidence'], ['best-evidence'],
    `Millville had once been a thriving mill town, its economy built on the textile factory that employed nearly half the population. When the factory moved operations overseas in 2008, the town began a slow unraveling. Half the storefronts on Main Street displayed "For Lease" signs, their windows dark and dusty. The diner still opened at 6 a.m., but the breakfast crowd had thinned to a handful of regulars who nursed their coffee and talked about the old days. The high school, which had graduated 200 students a year in its prime, now barely managed 80. Young people left for the city as soon as they could. Those who stayed did so out of loyalty, stubbornness, or lack of options. The town council met monthly to discuss "revitalization strategies," but the meetings had the tired quality of people who have been hoping for too long.`),

  mkQ('ela.reading.inference', randDiff(), 'What does this passage suggest about the narrator\'s character?',
    'The narrator is compassionate and observant, noticing people others overlook.',
    'The narrator is judgmental of homeless people.', 'The narrator is wealthy and privileged.', 'The narrator doesn\'t care about others.',
    'Noticing details about the homeless man and reflecting on him shows empathy and awareness.',
    'The passage shows the opposite—compassion', 'No wealth indicators are present',
    ['reading-comprehension', 'inference'], ['inference'],
    `The man at the corner of Fifth and Broadway had a system. Every morning he arranged his belongings in the same precise order: sleeping bag rolled tight against the wall, cardboard sign propped at exactly the right angle to catch the morning sun, cup positioned at arm's length. Most commuters walked past without seeing him—he was part of the scenery, like the fire hydrant or the newspaper box. But I noticed things. His shoes were always tied. His beard was trimmed. The book in his lap changed every few days—last week it was Steinbeck, this week Toni Morrison. Once, our eyes met and he nodded with a dignity that made me feel like the smaller person. I started leaving books on the bench near his spot. Never directly—that felt intrusive. Just nearby. They were always gone by evening.`),

  mkQ('ela.reading.claim_evidence', randDiff(), 'What claim is best supported?',
    'Hands-on learning can engage students who struggle with traditional instruction.',
    'All students learn best by doing.', 'Textbooks are useless.', 'Only science classes benefit from hands-on learning.',
    'Jaylen\'s transformation from struggling to engaged through hands-on work supports this claim.',
    'The passage describes a specific case, not a universal rule', 'Textbooks aren\'t discussed',
    ['reading-comprehension', 'claim-evidence'], ['claim-evidence'],
    `Jaylen had been labeled a "reluctant learner" since third grade. He fidgeted through lectures, lost worksheets, and stared out windows while teachers talked. His test scores suggested he was below average. Then he enrolled in Mr. Washington's engineering elective. On the first day, Mr. Washington handed each student a box of random materials—cardboard tubes, rubber bands, paper clips, tape—and said, "Build something that can hold a textbook three feet off the ground." Jaylen barely looked up for the entire period. His structure was the only one that worked on the first try. Over the semester, Jaylen designed a water filtration system for a class project that his science teacher called "graduate-level thinking." His other grades improved too—not because the content changed, but because, for the first time, Jaylen believed he was capable of learning.`),

  mkQ('ela.reading.inference', randDiff(), 'What can you infer about the relationship between the two characters?',
    'They are old friends reconnecting after years apart, navigating how they\'ve changed.',
    'They are meeting for the first time.', 'They are enemies.', 'They are coworkers.',
    'References to shared memories and noticing changes suggest a reunion of old friends.',
    'Their shared history contradicts first meeting', 'The warm tone contradicts animosity',
    ['reading-comprehension', 'inference'], ['inference'],
    `"You cut your hair," Amara said, the words out before she could stop them. Lena laughed—the same laugh, even after seven years. "You noticed." They stood in the restaurant doorway, neither quite sure whether to hug or shake hands or just stand there. They had been inseparable once, freshman year through senior year, until college took them to different coasts and time did what it does. Now Lena wore glasses and spoke with a slight accent she'd picked up in Barcelona. Amara had a scar on her wrist from the cooking accident she'd mentioned in an email three years ago. They noticed everything about each other—what had changed, what hadn't. "You still bite your lip when you're nervous," Lena said. Amara laughed. "And you still notice everything." They hugged. It wasn't awkward at all.`),

  mkQ('ela.reading.best_evidence', randDiff(), 'Which evidence best supports the inference that the character is making a sacrifice?',
    '"She folded the acceptance letter and placed it back in the envelope, then opened her laptop to the community college website."',
    '"The mailbox was full."', '"Her mother was cooking dinner."', '"The sun was setting."',
    'Choosing community college over an acceptance she received shows she\'s giving something up.',
    'Irrelevant detail', 'Doesn\'t indicate sacrifice',
    ['reading-comprehension', 'evidence'], ['best-evidence'],
    `The envelope from Stanford was thick—always a good sign. Elena opened it in the driveway, not wanting to share the moment until she knew what it held. "Congratulations," the letter began, and her heart soared for exactly three seconds. Then she thought about the numbers—tuition, room, board, books—and her heart returned to earth. Her mother worked two jobs and still couldn't cover the rent some months. Her younger brother needed braces. The scholarship covered half, which still left an impossible gap. Elena sat on the front steps for a long time. She folded the acceptance letter and placed it back in the envelope, then opened her laptop to the community college website. Their nursing program had a 95% job placement rate. She could live at home, help with bills, and transfer later. Maybe. She typed in her information and pressed "Apply." The sunset behind her was beautiful, but she didn't turn around to see it.`),

  mkQ('ela.reading.inference', randDiff(), 'What can you infer about the town\'s attitude toward the newcomer?',
    'The town is suspicious of outsiders but gradually warming to her through her actions.',
    'Everyone immediately welcomed her.', 'The town hates all newcomers.', 'She is from the same town.',
    'Initial distance followed by small gestures of acceptance shows gradual warming.',
    'The initial suspicion contradicts this', 'The passage shows them opening up, not permanent rejection',
    ['reading-comprehension', 'inference'], ['inference'],
    `Dr. Adebayo arrived in Pineville on a Tuesday, and by Wednesday the whole town knew her business—or thought they did. "Another city doctor who'll leave in six months," said Frank at the hardware store. The previous three doctors had lasted a year at most before the isolation drove them back to larger hospitals. Dr. Adebayo unpacked her office slowly, hanging her diplomas next to a photo of her grandmother, who had been a village healer in Nigeria. She made house calls, which none of the previous doctors had done. She learned names. When old Mrs. Henderson's cat was sick, Dr. Adebayo drove her to the veterinarian forty miles away, because Mrs. Henderson couldn't drive at night. It wasn't a grand gesture. But the next morning, Frank left a jar of his wife's preserves on the clinic doorstep with a note: "Welcome to Pineville. We hope you stay."`),

  mkQ('ela.reading.claim_evidence', randDiff(), 'What claim does this passage best support?',
    'Access to nature has measurable positive effects on mental health.',
    'Everyone should move to the countryside.', 'Cities are uninhabitable.', 'Nature cures all illnesses.',
    'The studies cited show specific mental health benefits from nature exposure.',
    'The passage discusses urban green spaces too, not just countryside', 'The passage discusses specific benefits, not cure-alls',
    ['reading-comprehension', 'claim-evidence'], ['claim-evidence'],
    `A growing body of research demonstrates that exposure to natural environments has significant mental health benefits. A Stanford study found that a 90-minute walk in nature reduced activity in the prefrontal cortex region associated with rumination—the repetitive negative thinking linked to depression. Japanese researchers have documented that "forest bathing" (shinrin-yoku)—simply spending time among trees—lowers cortisol levels, reduces blood pressure, and boosts immune function. In urban settings, residents with views of green space from their windows report 30% fewer symptoms of depression than those with views of buildings. Children with ADHD show improved concentration after just 20 minutes in a park. These findings have prompted cities from Singapore to Vienna to invest in urban green infrastructure, recognizing that access to nature is not a luxury but a public health necessity.`),
];

// ===== LITERARY EXTRAS (33 needed) =====
const literaryExtras: Question[] = [
  mkQ('ela.reading.figurative_language', randDiff(), 'What literary device is "her laughter was music, filling every corner of the room"?',
    'Metaphor', 'Simile', 'Hyperbole', 'Onomatopoeia',
    'Directly equating laughter to music without "like" or "as" makes it a metaphor.',
    'No "like" or "as" present', 'Not an exaggeration—it\'s a comparison',
    ['literary-analysis'], ['literary', 'figurative-language'],
    `Sarah's grandmother was the kind of person who made a room brighter just by entering it. Her laughter was music, filling every corner of the room and making strangers smile without knowing why. She told stories in a voice that rose and fell like ocean waves, pulling listeners in and carrying them away to places they'd never been. Even her silences had warmth—she could say more with a raised eyebrow than most people said in paragraphs. When she passed away last spring, the house didn't just feel empty. It felt muted, as if someone had turned down the volume on the world.`),

  mkQ('ela.reading.tone_mood', randDiff(), 'What is the tone of this passage?',
    'Ominous and foreboding', 'Cheerful and lighthearted', 'Neutral and objective', 'Angry and confrontational',
    'Dark imagery, silence, and the sense of something wrong create an ominous mood.',
    'The imagery is dark and unsettling', 'The passage conveys strong emotion through description',
    ['literary-analysis'], ['literary', 'tone-mood'],
    `The forest had gone quiet in the way that forests do when something is wrong. No birdsong, no rustle of small animals in the underbrush—just the creak of branches overhead and the sound of Elara's own breathing, too loud in the stillness. The path she had followed for an hour had narrowed to almost nothing, and the trees pressed close on either side, their bark dark and slick with moss. Somewhere ahead, a branch snapped. Elara stopped. The silence that followed was deeper than before, heavy with the weight of unseen things watching from the shadows. She had the sudden, irrational certainty that the forest did not want her here.`),

  mkQ('ela.reading.vocabulary_in_context', randDiff(), 'What does "threadbare" most likely mean in this context?',
    'Worn thin and showing signs of long use', 'Brand new and expensive', 'Colorful and decorative', 'Thick and warm',
    'The context of old furniture and faded photos suggests "threadbare" means worn from use.',
    'Contradicted by context clues', 'Not supported by surrounding description',
    ['literary-analysis'], ['literary', 'vocabulary'],
    `The apartment told the story of a life lived frugally but fully. The furniture was threadbare—the armchair's fabric worn smooth where countless evenings had been spent reading, the rug faded along the path between the kitchen and the living room. Photographs in mismatched frames crowded every surface: graduations, weddings, birthdays spanning decades. The bookshelves sagged under the weight of a lifetime of reading. Everything was old, everything was used, and everything was kept because it meant something.`),

  mkQ('ela.reading.plot_character', randDiff(), 'How does the protagonist change by the end of this passage?',
    'She moves from fear and self-doubt to confidence and self-acceptance.',
    'She becomes more afraid.', 'She gives up on her goal.', 'She doesn\'t change at all.',
    'The progression from trembling hands to "she belonged here" shows growing confidence.',
    'Her final actions contradict increased fear', 'She accomplishes what she set out to do',
    ['literary-analysis'], ['literary', 'character-development'],
    `Zoe's hands trembled as she approached the microphone. Three hundred faces stared back at her from the auditorium seats—some bored, some curious, a few openly smirking. She had never spoken in front of more than five people, and those five had been her family, who were contractually obligated to be supportive. Her speech was about climate change. She had memorized every word, but now they jumbled together in her head like a dropped deck of cards. She opened her mouth. Nothing came out. Someone in the back row coughed. Zoe closed her eyes and thought about the melting glaciers she'd read about—real ice, real water, real consequences. She opened her eyes. "Our planet is speaking to us," she said, and her voice didn't shake at all. "The question is whether we're listening." By the time she finished, the auditorium was quiet—not bored-quiet, but listening-quiet. She walked off stage knowing, for the first time, that she belonged here.`),

  mkQ('ela.reading.figurative_language', randDiff(), 'What does "his words were a knife, cutting through the comfortable silence" represent?',
    'His words were harsh and disruptive, breaking a peaceful moment.', 'He was holding a knife.', 'He spoke quietly.', 'The silence was uncomfortable.',
    'The metaphor compares words to a knife to show their sharp, disruptive effect.',
    'Literal reading—it\'s figurative', 'The silence is described as comfortable',
    ['literary-analysis'], ['literary', 'figurative-language'],
    `They had been sitting on the porch for twenty minutes without speaking, and it was the best twenty minutes of Caleb's day. The crickets chirped, the swing creaked gently, and the stars were doing what stars do—being impossibly far away and impossibly beautiful at the same time. Then his father cleared his throat, and Caleb knew. He always knew. "Your mother and I have decided—" his father began, and his words were a knife, cutting through the comfortable silence and leaving something ragged in its place. Caleb kept his eyes on the stars. They, at least, hadn't changed.`),

  mkQ('ela.reading.tone_mood', randDiff(), 'What mood does this passage create?',
    'Tense and claustrophobic', 'Peaceful and serene', 'Excited and energetic', 'Bored and listless',
    'The cramped space, counting heartbeats, and waiting create tension and claustrophobia.',
    'Every detail adds to unease', 'The stillness is anxious, not calm',
    ['literary-analysis'], ['literary', 'tone-mood'],
    `The closet was smaller than Alia remembered. Or maybe she was bigger now—twelve years old and folded into a space meant for coats and umbrellas, her knees pressed against the door, her back against the wall. She could hear the footsteps in the hallway, slow and deliberate. Not her mother's quick, purposeful stride or her brother's careless thudding. These footsteps belonged to someone who was looking. Alia held her breath and counted her heartbeats: one, two, three, four. The footsteps stopped outside the closet door. A shadow broke the line of light at the bottom. Alia's heart was at forty-seven when the shadow moved on. She didn't exhale until sixty.`),

  mkQ('ela.reading.figurative_language', randDiff(), 'What type of figurative language is "time crawled like a wounded animal"?',
    'Simile', 'Metaphor', 'Personification', 'Alliteration',
    '"Like" signals a simile comparing the passage of time to a wounded animal\'s slow movement.',
    'Uses "like"—simile not metaphor', 'Comparing time to an animal, not giving it human qualities',
    ['literary-analysis'], ['literary', 'figurative-language'],
    `The waiting room of the emergency department existed outside of normal time. Here, minutes stretched and sagged, each one heavy with worry and fluorescent light. For David, sitting in the hard plastic chair with his daughter's blood still on his shirt, time crawled like a wounded animal. Every time the double doors swung open, his heart lurched. Every announcement over the intercom sent electricity through his veins. The television mounted in the corner played a cooking show at low volume—someone was making risotto, stirring slowly, as if the world outside this room still functioned normally. David stared at it without seeing. His entire universe had narrowed to the width of those double doors and whatever news would eventually walk through them.`),

  mkQ('ela.reading.vocabulary_in_context', randDiff(), 'What does "kindling" mean as used in this passage?',
    'Material used to start a fire; here metaphorically meaning the spark that ignited his passion',
    'Being kind to others', 'Small pieces of wood only', 'Preventing a fire',
    'In context, the books and ideas served as "kindling" that started his intellectual passion.',
    'Not the meaning in this context', '"Kindling" here is figurative, not just literal',
    ['literary-analysis'], ['literary', 'vocabulary'],
    `Before he discovered the library, Jerome's anger had no direction—it was a wildfire burning everything equally. But Mrs. Torres, the librarian, handed him a book one Tuesday afternoon, almost carelessly, as if it weren't the most important thing that would happen to him all year. "Try this," she said. It was James Baldwin's "The Fire Next Time." Jerome read it in one sitting, then read it again. Baldwin's words were kindling of a different kind—they didn't start fires, they focused them. They gave Jerome's anger a shape, a language, a history. Within months, Jerome had read every Baldwin book in the library. Then he moved on to Langston Hughes, then Toni Morrison, then bell hooks. His anger didn't disappear. It became something sharper, more useful—a tool instead of a weapon.`),

  mkQ('ela.reading.plot_character', randDiff(), 'What does this passage reveal about the father?',
    'He struggles to express love verbally but shows it through actions.',
    'He doesn\'t love his children.', 'He is very emotional and expressive.', 'He is absent from his children\'s lives.',
    'Waking early, making breakfast, and the struggle with words show love through actions.',
    'His actions contradict this', 'He\'s reserved, not openly emotional',
    ['literary-analysis'], ['literary', 'character-development'],
    `My father was not a man of words. In twenty years, I never once heard him say "I love you"—not to me, not to my mother, not to anyone. Words, for him, were functional things: "Pass the salt." "Time for school." "Drive safe." But every morning of my childhood, I woke to the smell of breakfast—eggs and toast, exactly the way each of us liked them, because he had memorized our preferences without ever asking. He drove forty minutes to my soccer games and stood alone on the sideline, never cheering but never looking away. When I got accepted to college, he didn't say he was proud. He went to the garage and built me a desk for my dorm room. I found a note inside the drawer, in his careful handwriting: "Study hard." It was the longest letter he ever wrote me, and I have kept it for fifteen years.`),

  mkQ('ela.reading.figurative_language', randDiff(), 'What literary device is the phrase "hope is the thing with feathers"?',
    'Metaphor (comparing hope to a bird)', 'Simile', 'Onomatopoeia', 'Hyperbole',
    'Emily Dickinson directly equates hope with a feathered creature—a metaphor.',
    'No "like" or "as"—it\'s a metaphor', 'No sound words present',
    ['literary-analysis'], ['literary', 'figurative-language'],
    `Maya had always loved Emily Dickinson's line: "Hope is the thing with feathers that perches in the soul." On her worst days—and there had been many lately—she would close her eyes and try to feel it, that small flutter in her chest that meant tomorrow might be different. Some days the bird was silent, wings folded tight, barely breathing. Other days it sang so loudly she could almost convince herself that everything would be okay. Today, sitting in the hospital room while machines beeped their steady rhythms and her mother slept, the bird was quiet but present. Not singing, not soaring, but there—perched on some invisible branch inside her, refusing to leave.`),

  mkQ('ela.reading.tone_mood', randDiff(), 'What is the overall tone of this passage?',
    'Nostalgic with underlying sadness', 'Purely joyful', 'Angry and resentful', 'Indifferent and detached',
    'Looking back fondly at memories that can\'t be recaptured creates bittersweet nostalgia.',
    'The awareness of loss tempers any pure joy', 'The passage shows deep emotional engagement',
    ['literary-analysis'], ['literary', 'tone-mood'],
    `Summer at Grandma's house was measured in popsicle stains and firefly jars. We ran barefoot through grass that needed cutting, and nobody worried about tetanus or screen time or college applications. The world was the backyard, and the backyard was infinite. Grandma would call us in for dinner at a time that seemed determined not by clocks but by the angle of the sun, and we'd eat corn on the cob with butter dripping down our chins, competing to see who could eat the fastest. After dinner, we caught fireflies and kept them in Mason jars with holes poked in the lids, watching them blink their cold green light like tiny, confused stars. We always let them go before bed. "Everything deserves to be free," Grandma said. She sold the house last year. I drove past it on the way to somewhere else and almost didn't recognize it. The grass was cut. The fireflies, I imagine, had found somewhere else to be confused.`),

  mkQ('ela.reading.figurative_language', randDiff(), 'What is the effect of personifying the city in this passage?',
    'It makes the city feel alive and responsive to the character\'s emotions.',
    'It makes the passage confusing.', 'It suggests the city is dangerous.', 'It has no effect.',
    'Giving the city human qualities creates an emotional connection between character and setting.',
    'The personification enhances understanding', 'The city is described as welcoming, not threatening',
    ['literary-analysis'], ['literary', 'figurative-language'],
    `New York welcomed Priya the way it welcomes everyone—with noise, indifference, and an overwhelm that feels, if you squint, like excitement. The subway breathed her underground and exhaled her at the wrong stop, and the buildings leaned over her like curious giants. The city didn't care about her—that was its gift. For the first time in her life, she was anonymous, invisible, free to be whoever she wanted without a single person who knew her old self. The city opened its arms and said nothing, because it had seen a million versions of her story. She walked sixty blocks that first night, lost and exhilarated, and the city walked with her, never sleeping, never judging, lighting her path with neon and streetlamp and the glow of a thousand windows where a thousand lives were happening simultaneously.`),

  mkQ('ela.reading.plot_character', randDiff(), 'What internal conflict does the narrator face?',
    'The tension between pursuing personal ambition and family obligation',
    'Choosing between two colleges', 'Deciding what to eat', 'Whether to exercise',
    'The pull between the scholarship and helping the family business shows ambition vs. duty.',
    'The conflict is deeper than a simple choice', 'Not addressed in the passage',
    ['literary-analysis'], ['literary', 'character-development'],
    `The scholarship letter sat on the kitchen counter for a week. Full ride. Four years. A thousand miles away. My mother didn't mention it, which was her way of saying everything. She kneaded bread dough with the same hands that had kneaded it for thirty years, in the same bakery her mother had opened, in the same town where five generations of our family had lived and worked and died. I was the first to finish high school. I was supposed to be the first to go to college. But I was also the only one who knew how to fix the oven when it ran too hot, the only one who understood the sourdough starter, the only one my mother could lean on now that my father was gone. "You should go," she said one morning, still kneading. "You should go and not feel guilty." But I heard what she didn't say—the pause before "go," the breath that caught—and I felt guilty anyway.`),

  mkQ('ela.reading.vocabulary_in_context', randDiff(), 'What does "sanctuary" mean as used here?',
    'A safe place of refuge and peace', 'A church', 'A zoo', 'A bedroom',
    'In context, the garden serves as a place of emotional safety and escape from stress.',
    'While sanctuaries can be churches, here it\'s figurative', 'Not a literal definition used here',
    ['literary-analysis'], ['literary', 'vocabulary'],
    `The garden behind the apartment building was, by any objective measure, not much to look at—a few raised beds made from reclaimed wood, some herbs that had survived more through stubbornness than care, and a single rosebush that bloomed defiantly every June. But for Mrs. Okafor, it was a sanctuary. When the walls of her apartment felt too close and the noise of the city too loud, she would step outside with her watering can and her thoughts, and somehow both the plants and her mind would settle. She talked to the rosebush sometimes—not because she believed it could hear, but because saying things out loud to something alive felt different than saying them to an empty room.`),

  mkQ('ela.reading.tone_mood', randDiff(), 'What tone shift occurs in this passage?',
    'From playful humor to genuine vulnerability', 'From sadness to anger', 'From excitement to boredom', 'No tone shift occurs',
    'The passage moves from jokes and laughter to the admission about not being okay.',
    'Both emotions are present, not just the first', 'The shift is clearly marked',
    ['literary-analysis'], ['literary', 'tone-mood'],
    `Marcus was the funny one. Everyone said so. He was the guy who turned a boring Tuesday lunch into a comedy show, who could make even Mr. Peterson—the most humorless math teacher in the history of education—crack a smile during a lesson on quadratic equations. His timing was impeccable, his impressions were uncanny, and his ability to find the absurd in the ordinary was a genuine talent. What nobody knew, because Marcus was very, very good at his job, was that the comedy was a wall. On the other side of that wall lived a boy who hadn't slept through the night in months, who cried in the shower because it was the only place loud enough to cover the sound, and who had Googled "therapists near me" seventeen times without ever making a call. "You're always so happy," his friends said. Marcus smiled his famous smile. "Yeah," he said. "I'm great."`),

  mkQ('ela.reading.figurative_language', randDiff(), 'What does the "wall" metaphor in this passage represent?',
    'The humor Marcus uses to hide his pain from others',
    'A physical wall in his house', 'His school building', 'His friendship group',
    'The wall is explicitly described as the comedy that conceals his true emotional state.',
    'The passage makes clear it\'s figurative', 'It separates his public and private selves',
    ['literary-analysis'], ['literary', 'figurative-language'],
    `Marcus was the funny one. Everyone said so. He was the guy who turned a boring Tuesday lunch into a comedy show, who could make even Mr. Peterson—the most humorless math teacher in the history of education—crack a smile during a lesson on quadratic equations. His timing was impeccable, his impressions were uncanny, and his ability to find the absurd in the ordinary was a genuine talent. What nobody knew, because Marcus was very, very good at his job, was that the comedy was a wall. On the other side of that wall lived a boy who hadn't slept through the night in months, who cried in the shower because it was the only place loud enough to cover the sound, and who had Googled "therapists near me" seventeen times without ever making a call. "You're always so happy," his friends said. Marcus smiled his famous smile. "Yeah," he said. "I'm great."`),

  mkQ('ela.reading.plot_character', randDiff(), 'What does this passage reveal about Coach Kim?',
    'She values effort and growth over natural talent.',
    'She only cares about winning.', 'She is unfair to talented players.', 'She doesn\'t know much about basketball.',
    'Choosing the hardest worker over the most talented shows her values.',
    'She recognizes talent but prioritizes effort', 'Her decision shows deep basketball understanding',
    ['literary-analysis'], ['literary', 'character-development'],
    `Coach Kim had to choose a team captain, and everyone assumed it would be Destiny. Destiny was the most talented player on the team—everyone knew it, including Destiny herself. She could hit three-pointers with her eyes closed and dribble through double teams like they weren't there. But Coach Kim chose Aaliyah instead. Aaliyah, who had been cut from the team as a freshman and tried out again as a sophomore. Aaliyah, who stayed after every practice to shoot free throws until the custodian turned off the lights. Aaliyah, who wasn't the best player on the team but made everyone around her better. "Talent is a gift," Coach Kim told the team. "Work ethic is a choice. I'd rather follow someone who chose to be here than someone who was born here." Destiny was furious. By the end of the season, she understood.`),

  mkQ('ela.reading.figurative_language', randDiff(), 'What does "the silence between them was a living thing" mean?',
    'The unspoken tension was so palpable and significant it felt like a physical presence.',
    'Something was literally alive in the room.', 'They were both very quiet people.', 'The room had good soundproofing.',
    'Personifying silence as "living" emphasizes how powerfully present and uncomfortable it was.',
    'The passage is figurative', 'Their silence is weighted with meaning',
    ['literary-analysis'], ['literary', 'figurative-language'],
    `After the argument, the silence between them was a living thing. It sat at the dinner table in the empty chair, it walked between them in the hallway, it lay in the bed at night, taking up more space than either of them. They moved around it carefully, the way you move around a piece of furniture in the dark, afraid of bumping into something that would hurt. Elena wanted to speak first but couldn't find words large enough for what needed saying. Miguel wanted to apologize but worried that words would make it worse. So the silence grew, fed by all the things they didn't say, until it was larger than the apartment, larger than both of them, a third presence in a two-person home.`),

  mkQ('ela.reading.tone_mood', randDiff(), 'What mood does this passage create?',
    'Awe and wonder at the natural world', 'Boredom and indifference', 'Anxiety and fear', 'Sadness and grief',
    'The vivid descriptions of natural beauty and the narrator\'s emotional response create wonder.',
    'The narrator is deeply engaged, not bored', 'The experience is positive, not frightening',
    ['literary-analysis'], ['literary', 'tone-mood'],
    `The first time I saw the aurora borealis, I forgot how to breathe. Green light rippled across the sky like silk curtains blown by an invisible wind. Then purple arrived, then pink, then a white so bright it looked like the sky had cracked open to reveal something luminous behind it. I stood in a field in Iceland, seventeen years old, my neck bent back so far it ached, and I understood for the first time what the word "sublime" meant—not just beautiful, but beautiful in a way that makes you feel small and enormous at the same time. The lights danced for three hours. I didn't move for any of them. When they finally faded, I sat down in the frozen grass and cried, not from sadness but from the overwhelming sensation of having been shown something I didn't know the world could do.`),
];

// Load existing and append
function appendToFile(filename: string, extras: Question[]) {
  const path = resolve(outDir, filename);
  const existing: Question[] = JSON.parse(readFileSync(path, 'utf-8'));
  const combined = [...existing, ...extras];
  writeFileSync(path, JSON.stringify(combined, null, 2));
  console.log(`${filename}: ${existing.length} + ${extras.length} = ${combined.length}`);
}

appendToFile('round2_ela_main_idea.json', mainIdeaExtras);
appendToFile('round2_ela_inference.json', inferenceExtras);
appendToFile('round2_ela_literary.json', literaryExtras);
